### ISSUE TITLE
OracleBulkCopy exception ORA-01013: user requested cancel of current operation

### ISSUE THREAD

**Issue by protokovich** [oracle/dotnet-db-samples#133]
On any oracle db:

```csharp
OracleConfiguration.AddOracleTypesDeserialization();

var bc = new Oracle.ManagedDataAccess.Client.OracleBulkCopy(con, OracleBulkCopyOptions.Default);
bc.BatchSize = 10000;
bc.DestinationSchemaName = "SYS";
bc.DestinationTableName = "TMP_TAB";
bc.BulkCopyTimeout = 1200;

bc.WriteToServer(dt); // ! exception here 
```

> Oracle.ManagedDataAccess.Client.OracleException: 'ORA-01013: user requested cancel of current operation'

  

>  at OracleInternal.ServiceObjects.OracleConnectionImpl.CheckForAnyErrorFromDB(TTCError ttcOER)
>    at OracleInternal.TTC.TTCDirectPathPrepare.ReadResponse(DirectPathContext& directPathContext)
>    at OracleInternal.ServiceObjects.OracleBulkCopyImpl.Prepare()
>    at Oracle.ManagedDataAccess.Client.OracleBulkCopy.WriteDataSourceToServer(IBulkCopyDataSource dataSource)
>    at Oracle.ManagedDataAccess.Client.OracleBulkCopy.WriteToServer(DataTable table, DataRowState rowState)
>    at Oracle.ManagedDataAccess.Client.OracleBulkCopy.WriteToServer(DataTable table)
>    at oracle_bulkcopy_console_test.Program.Main(String[] args) in d:\source\repos\oracle_bulkcopy_console_test\oracle_bulkcopy_console_test\Program.cs:line 73

I don't cancel any transactions

**Comment by protokovich** [comment]
destination column name in ColumnMapping must be ToUpper()
