### ISSUE TITLE
Scaffold-DbContext continuous and multiple errors

### ISSUE THREAD

**Issue by ollie10** [oracle/dotnet-db-samples#135]
Hello Everyone,

I'm trying to connect **Entity Framework** with an **Oracle Autonomous Database** on **Oracle Cloud**.

I downloaded the wallet from Oracle Cloud Website correctly as explained [here ](https://www.oracle.com/database/technologies/appdev/dotnet/adbdotnetquickstarts.html)in "obtain client credentials".
I tried first to use a tool called [EF Core Power Tools](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools) without any luck. I thought the problem was on the tool's side but I see that this doesn't work also with the normal scaffolding process.

I have a simple Console Application and the **Oracle Tools for Visual Studio** installed, in fact I can connect with the **Server Explorer** to the database.

I have all the files of the wallet downloaded in the **root path** of the console application (as I read in a [StackOverflow post](https://stackoverflow.com/a/64650606)) and I launch the command: 
`Scaffold-DbContext "Data Source=_mydbname_high;Password=_mypassword_;User Id=ADMIN;Connection Timeout=120;" Oracle.EntityFrameworkCore -OutputDir Models`

And I get this error:

_2021-01-04 16:50:58.938662 ThreadID:1   (ERROR)   OracleDatabaseModelFactory.Create() :  Oracle.ManagedDataAccess.Client.OracleException (0x80004005): Trasporto di rete: errore SSL durante l'analisi della posizione del wallet
 ---> OracleInternal.Network.NetworkException (0x80004005): Trasporto di rete: errore SSL durante l'analisi della posizione del wallet
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at OracleInternal.Common.SqlNetOraConfig.HandlePathSeparators(String WalletDirectory)
   at OracleInternal.Network.TcpsTransportAdapter.Negotiate(ConnectionOption conOption)
   at OracleInternal.Network.OracleCommunication.DoConnect(String tnsDescriptor)
   at OracleInternal.Network.OracleCommunication.Connect(String tnsDescriptor, Boolean doNAHandshake, String IName, ConnectionOption CO)
   at OracleInternal.ServiceObjects.OracleConnectionImpl.Connect(ConnectionString cs, Boolean bOpenEndUserSession, OracleConnection connRefForCriteria, String instanceName)
   at OracleInternal.ConnectionPool.PoolManager`3.Get(ConnectionString csWithDiffOrNewPwd, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)
   at OracleInternal.ConnectionPool.OraclePoolManager.Get(ConnectionString csWithNewPassword, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)
   at OracleInternal.ConnectionPool.OracleConnectionDispenser`3.Get(ConnectionString cs, PM conPM, ConnectionString pmCS, SecureString securedPassword, SecureString securedProxyPassword, OracleConnection connRefForCriteria)
   at Oracle.ManagedDataAccess.Client.OracleConnection.Open()
   at Oracle.EntityFrameworkCore.Scaffolding.Internal.OracleDatabaseModelFactory.Create(DbConnection connection, IEnumerable`1 tables, IEnumerable`1 schemas)
Oracle.ManagedDataAccess.Client.OracleException (0x80004005): Trasporto di rete: errore SSL durante l'analisi della posizione del wallet
 ---> OracleInternal.Network.NetworkException (0x80004005): Trasporto di rete: errore SSL durante l'analisi della posizione del wallet
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at OracleInternal.Common.SqlNetOraConfig.HandlePathSeparators(String WalletDirectory)
   at OracleInternal.Network.TcpsTransportAdapter.Negotiate(ConnectionOption conOption)
   at OracleInternal.Network.OracleCommunication.DoConnect(String tnsDescriptor)
   at OracleInternal.Network.OracleCommunication.Connect(String tnsDescriptor, Boolean doNAHandshake, String IName, ConnectionOption CO)
   at OracleInternal.ServiceObjects.OracleConnectionImpl.Connect(ConnectionString cs, Boolean bOpenEndUserSession, OracleConnection connRefForCriteria, String instanceName)
   at OracleInternal.ConnectionPool.PoolManager`3.Get(ConnectionString csWithDiffOrNewPwd, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)
   at OracleInternal.ConnectionPool.OraclePoolManager.Get(ConnectionString csWithNewPassword, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)
   at OracleInternal.ConnectionPool.OracleConnectionDispenser`3.Get(ConnectionString cs, PM conPM, ConnectionString pmCS, SecureString securedPassword, SecureString securedProxyPassword, OracleConnection connRefForCriteria)
   at Oracle.ManagedDataAccess.Client.OracleConnection.Open()
   at Oracle.EntityFrameworkCore.Scaffolding.Internal.OracleDatabaseModelFactory.Create(DbConnection connection, IEnumerable`1 tables, IEnumerable`1 schemas)
   at Oracle.EntityFrameworkCore.Scaffolding.Internal.OracleDatabaseModelFactory.Create(DbConnection connection, DatabaseModelFactoryOptions options)
   at Oracle.EntityFrameworkCore.Scaffolding.Internal.OracleDatabaseModelFactory.Create(String connectionString, DatabaseModelFactoryOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Trasporto di rete: errore SSL durante l'analisi della posizione del wallet_

Which it's also strange since Windows is in English, Visual Studio is in English and I get the error in Italian (but this is not  a problem)

The problem is that there is no way to scaffold the database.
I lost the afternoon trying (adding configurations in AppSettings), environment variables and so on without any luck.

Just to mention that the same thing with SQL server, Postgres or MySql works in less than two minutes...
Any clue on what's happening?
Thanks

![scaffold](https://user-images.githubusercontent.com/10867372/103554929-f7e2a080-4eaf-11eb-9b65-503a7decf1dc.png)

**Comment by alexkeh** [comment]
@ollie10 
If you are running the app in VS debugging mode, can you try placing the wallet files in the project's debug working directory? I believe it would be something similar to

...ConsoleApp1\bin\Debug\netcoreapp3.1

depending on the .NET (Core) version you are using. You may also need to put your *.ora files there depending on how you configured your setup.

If you'd like your app to look for these files in a specific directory, set the OracleConfiguration.TnsAdmin and OracleConfiguration.WalletLocation properties to the directory that contains these files.

**Comment by ollie10** [comment]
Hi @alexkeh, thanks for replying, I was just trying and I saw **it worked** but without copying the files in that location which anyway I think I could do it changing the property of the file and setting it to content and copy always.

I managed to do it changing one file from the version I downloaded from **Oracle Cloud** to match my path
I changed so the **sqlnet.ora** from this:

```
WALLET_LOCATION = (SOURCE = (METHOD = file) (METHOD_DATA = (DIRECTORY="?/network/admin")))
SSL_SERVER_DN_MATCH=yes
```

To This:

```
WALLET_LOCATION = (SOURCE = (METHOD = file) (METHOD_DATA = (DIRECTORY="C:\Users\...\ myactualdir")))
SSL_SERVER_DN_MATCH=yes
```

This anyway it seems to me a workaround, which is the proper way to do it?
And I managed to make it work with **Scaffold-DbContext** but the optimal solution would be using **EF Core Power Tools**, I saw there are posts between you and them (see below) on Github, I tried to do as they explain using the last version but It didn't work, with their tool I have this error:

```
System.Exception: Table list error: 
Oracle.ManagedDataAccess.Client.OracleException (0x80004005): **ORA-12154**: TNS: impossibile risolvere l'identificativo di connessione specificato
```

Conversation: https://github.com/ErikEJ/EFCorePowerTools/issues/225
Reply: https://github.com/oracle/dotnet-db-samples/issues/73#issuecomment-660308368

**Comment by alexkeh** [comment]
For wallet directory resolution, using sqlnet.ora is fine. The other way is to set the WalletLocation, which can be done in your .NET config file or OracleConfiguration class. ODP.NET also recently added the property to the OracleConnection class and connection string. You can take your pick among any of these.

For the EF Core Power Tools issue, the error means that ODP.NET couldn't either find a connect descriptor that correlated to your TNS name or that the connect descriptor has something incorrectly set. What may be more likely is that EF Core Power Tools is not using the same ODP.NET instance as  your project. Thus, it could be using a different set of tnsnames.ora entries from your ADB instance.

One correction to my earlier post. You do have to set a wallet location. I don't believe we've defined a default one. Placing the *.ora files in the debug directory will work because the current working directory is where ODP.NET looks for *.ora files, but not wallet files. Thus, you need to set where to find the wallet file. In this case, you've done so in the sqlnet.ora file.

**Comment by ollie10** [comment]
Hello again @alexkeh, could you point some examples for set the WalletLocation, I tried with web config but it didn't work ([here](https://stackoverflow.com/a/47559915)). Also I would need a way that can be "transformable" since the wallet will not be in the same location in various environments.
Many thanks

**Comment by alexkeh** [comment]
- [OracleConnection.WalletLocation](https://docs.oracle.com/en/database/oracle/oracle-data-access-components/19.3.2/odpnt/ConnectionWalletLocation.html#GUID-F31F01E4-9065-4FDD-ADE3-F7315D196D5B)
- [OracleConfiguration.WalletLocation](https://docs.oracle.com/en/database/oracle/oracle-data-access-components/19.3.2/odpnt/ConfigurationWalletLocation.html#GUID-1CF9B2C8-83A4-4445-B7DD-ED1EB2DE0313)
- [Connection string Wallet_Location](https://docs.oracle.com/en/database/oracle/oracle-data-access-components/19.3.2/odpnt/ConnectionConnectionString.html#GUID-DF4ED9A3-1AAF-445D-AEEF-016E6CD5A0C0)
- [.NET Config file WALLET_LOCATION in the "settings" section](https://docs.oracle.com/en/database/oracle/oracle-data-access-components/19.3.2/odpnt/InstallManagedConfig.html#GUID-A9EF5624-1828-46DD-84D1-CC5F40BFB6F5)

**Comment by ollie10** [comment]
Hello @alexkeh thanks again, I suppose you meant the last two links, because for connecting at runtime I find a good looking example [here](https://www.oracle.com/database/technologies/appdev/dotnet/adbdotnetquickstarts.html) that it's pretty clear.

The problem comes with the scaffolding, I tried with your suggestions but no luck still ORA-12154 error.

**Test 1** changing the **App.config** so:

I moved all the files downloaded from **Oracle Cloud** in a subfolder named **Wallet** in the root of the project

```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
	<configSections>
		<section name="oracle.manageddataaccess.client" type="OracleInternal.Common.ODPMSectionHandler, Oracle.ManagedDataAccess, Version=4.121.2.0, Culture=neutral, PublicKeyToken=89b483f429c47342" />
	</configSections>
	<oracle.manageddataaccess.client>
		<version number="*">
			<settings>
				<setting name="TNS_ADMIN" value="C:\...\ConsoleApp1\Wallet" />
				<setting name="WALLET_LOCATION" value="C:\...\ConsoleApp1\Wallet" />
			</settings>
		</version>
	</oracle.manageddataaccess.client>
</configuration>
```



**Test 2** calling the command with the new parameter:

`Scaffold-DbContext "Data Source=_mydb_high_;Password=_password_;User Id=_user_;Connection Timeout=120;Wallet_Location=C:\....\ConsoleApp1\Wallet;" Oracle.EntityFrameworkCore -Force -OutputDir Models`

No luck in any case

**Comment by alexkeh** [comment]
ORA-12154 is generally a problem with the tnsnames.ora file, not the wallet file.  One thing to note is that Oracle EF Core is not officially supported in .NET FW. It may work, but it hasn't been tested. 

At the very least, I wouldn't recommend using app.config to set the TNS_ADMIN. I would set the equivalent property in the same place you are setting the wallet location.  In your Test 2, you can include the Tns_Admin and set it to where your *.ora files are located.

**Comment by ollie10** [comment]
Hello @alexkeh It finally worked so you suggest to pass always the Tns_Admin and Wallet_Location to the command to scaffold everything?
And in the code use the corresponding properties at runtime to pass the folder with Wallet.

I post here the command if someone else needs it

`Scaffold-DbContext "Data Source=_mydb_;Password=_mypassword_$;User Id=_mysuer_;Connection Timeout=120;Tns_Admin=C:\...\ConsoleApp1\Wallet;Wallet_Location=C:\...\ConsoleApp1\Wallet;" Oracle.EntityFrameworkCore -Force -OutputDir Models`

I don't know what did you mean with .net framework but I'm on a console application with .NET Core 3.1 right now, no .NET framework.

I also read that **.NET 5.0** is not supported yet, is this correct?

I suppose it's everything, if I encounter more problems I will keep writing

**Comment by alexkeh** [comment]
I assumed you were using .NET Framework since you used an app.config file. .NET Core does not use these configuration files. Thus, setting any values in this file would not affect your app. If you are using .NET Core, that would explain why Test 1 did not work.

In the case of EF Core, developers generally won't reference ODP.NET classes directly. Thus, setting the TNS and wallet location values in the connection string is the most common way.

ODP.NET Core 19.10 supports .NET 5. EF Core 5 will be supported later this month.

**Comment by ollie10** [comment]
You are right I used it because I found that as the only example, I would have used the appsettings in other cases, so I assume that for running the app configuring it in the connection string and scaffolding using it directly in the command line is the right way of doing it, now it seems it's all clear many thanks, I hope I will find the way to run it with EF Core Power Tools
Many thanks
