### ISSUE TITLE
Entity Framework Core 5 doesnt support Oracle 10G?

### ISSUE THREAD

**Issue by Dubawi** [oracle/dotnet-db-samples#150]
I'm trying to create a Model from my database Oracle(10g) using Scaffold-DbContext.

Scaffold-DbContext "DATA SOURCE=XPERTISE.world;PASSWORD=XXX;USER ID=SCHEDULE" Oracle.EntityFrameworkCore -OutputDir Models -Tables MEETINGS -Force.

Im getting this error. I created the database in 12C and 19C and was able to add the same table without problems.

2021-02-27 05:44:36.250848 ThreadID:1 (ERROR) OracleDatabaseModelFactory.Create() : Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-00904: "DEFAULT_COLLATION": invalid identifier
at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
at OracleInternal.ServiceObjects.OracleCommandImpl.VerifyExecution(OracleConnectionImpl connectionImpl, Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteReader(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl& rdrImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[] scnForExecution, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, Int64& internalInitialLOBFS, Int64 internalInitialJSONFS, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader()
at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteScalar()
at Oracle.EntityFrameworkCore.Scaffolding.Internal.OracleDatabaseModelFactory.<Create>g__GetCollation|9_0(DbConnection connection, String schema)
at Oracle.EntityFrameworkCore.Scaffolding.Internal.OracleDatabaseModelFactory.Create(DbConnection connection, IEnumerable`1 tables, IEnumerable`1 schemas)

**Comment by alexkeh** [comment]
Oracle EF Core 5 supports only Oracle DB 11.2.0.4 and higher versions.

**Comment by Dubawi** [comment]
Thank Alex.
