### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by wahmedswl** [oracle/dotnet-db-samples#159]
https://www.nuget.org/packages/Oracle.ManagedDataAccess/19.9.0

```
System.NullReferenceException: Object reference not set to an instance of an object.
         at OracleInternal.ServiceObjects.OracleGlobalizationImpl.SelectNLSValues(OracleConnection con)
         at OracleInternal.ServiceObjects.OracleConnectionImpl.GetGlobalizationValues(OracleGlobalizationImpl locGlobObj, OracleConnection con, Boolean isDB12101nAbove)
         at Oracle.ManagedDataAccess.Client.OracleConnection.GetSessionInfo()
         at Oracle.ManagedDataAccess.Client.OracleDataReader..ctor(OracleDataReaderImpl readerImpl, OracleConnection connection, Int64 fetchSize, Int64 clientInitialLOBFS, Int64 internalInitialLOBFS, Int32 initialLongFetchSize, Int32 recordsAffected, String commandText, SqlStatementType sqlStatementType, CommandBehavior behavior)
         at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
         at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader()
         at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteScalar()
```

Thanks

**Comment by alexkeh** [comment]
Can you share the code you are trying to execute?

**Comment by wahmedswl** [comment]
```
var superConnection = Database.Connection(DBCFG_DB_SCRIPTS);

            var sessionIds = new List<int>();
            var tasks = new List<Task>();
            for (int i = 0; i < 250; i++)
            {
                tasks.Add(SM.Do(() =>
                {
                    var connection = Database.Connection(DBCFG_DB_NORMAL);
                    var sessionId = connection.Field("m_sessionId", () => -1);
                    sessionIds.Add(sessionId);
                    Assert.True(superConnection.Scalar("SELECT COUNT(0) FROM V$SESSION A WHERE A.SID = :0", KVP: SM.KV("0", sessionId)).Int() > 0);
                    Disposer.Dispose(ref connection);
                }, onError: ex => Assert.True(false, ex.ToString())));
            }

            Task.WaitAll(tasks.ToArray());
            var testConnection = Database.Connection(DBCFG_DB_NORMAL);
            var testSessionId = testConnection.Field("m_sessionId", () => -1);
            sessionIds.Add(testSessionId);
            var totalSessions = superConnection.Scalar("SELECT COUNT(0) FROM V$SESSION A WHERE A.SID IN (:0)", KVP: SM.KV("0", sessionIds.ToArray())).Int();
            Disposer.Dispose(ref testConnection, clearPool: true);
            Assert.True(superConnection.Scalar("SELECT COUNT(0) FROM V$SESSION A WHERE A.SID IN (:0)", KVP: SM.KV("0", sessionIds.ToArray())).Int() < totalSessions);
            Disposer.Dispose(ref superConnection, clearPool: true);
```

**Comment by wahmedswl** [comment]
Hi, this is happening randomly and later run of Tests don't show this issue. 

Thanks

**Comment by alexkeh** [comment]
This seems like a timing or stress issue if it is not reproducing consistently. Can you open an SR with Oracle Support? We'll need additional diagnostic info to understand the root cause. It's hard to tell if this matches with an existing known issue without a more specific error or details of the circumstances the error always occurs under.

Another thing you could try is upgrade to ODP.NET 19.11 on NuGet Gallery. That would eliminate known issues that have already been fixed.
