### ISSUE TITLE
Presence of ValueGeneratedOnAddOrUpdate configuration results in errors in specific operations

### ISSUE THREAD

**Issue by danko007** [oracle/dotnet-db-samples#161]
Hi I'm using oracle 12.1c and Oracle.EntityFrameworkCore 3.19.80

After recent change of an entity-mapping from a table to an updatable view got the following error in the scenario beneath:

Microsoft.EntityFrameworkCore.DbUpdateException...
Inner Exception
InvalidCastException: Specified cast is not valid

`
// Mapped to a view with IsActive calculated as: case when From<sysdate and sysdate<Till then 'Y' else 'N' end as Is_Active;
class Subscription
    {
        public int Id { get; set; } // ValueGeneratedOnAdd
        public DateTime ValidFrom { get; set; }
        public DateTime ValidTill { get; set; }
        public bool IsActive { get; set; }// ValueGeneratedOnAddOrUpdate
    }
    class SubscriptionItem
    {
        public int Id { get; set; } // here (id, SubscriptionId) is a composite PK. Strange - no issues without Composite PK
        public int SubscriptionId { get; set; }
    }
    class Audit
    {
        public int Id { get; set; } // ValueGeneratedOnAdd
        public string Data { get; set; }
    }

var sub = db.Subscriptions.First();
                sub.ValidTill = x.ValidTill.AddDays(1);// no issues without the line
                db.SubscriptionItems.Add(new SubscriptionItem {Id = (int)(DateTime.Now.Ticks % 10000) , SubscriptionId = x.Id });
                db.AuditTrail.Add(new Audit { Data = "Data updated" });
                db.AuditTrail.Add(new Audit { Data = "Data added" }); // Strange - with the line commented out - no issues.
                db.SaveChanges();
`

**Comment by alexkeh** [comment]
This sounds similar to this Oracle EF Core known issue in the README/doc, but you probably would have seen an error on applying the update.

> If more than one column is associated with any Sequence/Trigger, then ValueGeneratedOnAdd() fluent API will be generated for each of these columns when performing a scaffolding operation. If we then use this scaffolded model to perform a migration, then an issue occurs because each of column that is associated with the ValueGeneratedOnAdd() fluent API is made an identity column by default. To avoid this issue, use UseOracleSQLCompatibility("11") which will force it to generate Triggers/Sequences instead. [Bug 29467919]

Anything odd about the schema once the migration was applied? I'm wondering what the data type casting is occurring that is leading to the error. Does the trace have any details?

**Comment by danko007** [comment]
I use Db-first. No migrations are involved.
Please see log below:

warn: Microsoft.EntityFrameworkCore.Model.Validation[10400]
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data, this mode should only be enabled during development.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.1.6 initialized 'MyDbContext' using provider 'Oracle.EntityFrameworkCore' with options: SensitiveDataLoggingEnabled DetailedErrorsEnabled OracleSQLCompatibility=11
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (95ms) [Parameters=[], CommandType='Text', CommandTimeout='0']
      SELECT "v"."ID", "v"."IS_ACTIVE", "v"."VALID_FROM", "v"."VALID_TILL"
      FROM "CONDPK"."V_SUBSCRIPTIONS" "v"
      where rownum <= 1
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (98ms) [Parameters=[:p0='Data updated' (Size = 2000), :p1='Data added' (Size = 2000), :p4='3280', :p5='1', :p3='1', :p2='2020-10-22T00:00:00' (DbType = DateTime), :cur1=NULL (Nullable = false) (Direction = Output) (DbType = Object), :cur2=NULL (Nullable = false) (Direction = Output) (DbType = Object), :cur3=NULL (Nullable = false) (Direction = Output) (DbType = Object)], CommandType='Text', CommandTimeout='0']
      DECLARE
      TYPE "rAUDIT_TRAIL_0" IS RECORD
      (
      "ID" NUMBER(10)
      );
      TYPE "tAUDIT_TRAIL_0" IS TABLE OF "rAUDIT_TRAIL_0";
      "lAUDIT_TRAIL_0" "tAUDIT_TRAIL_0";
      v3_IS_ACTIVE NVARCHAR2(2000);
      v_RowCount INTEGER;
      BEGIN
      "lAUDIT_TRAIL_0" := "tAUDIT_TRAIL_0"();
      "lAUDIT_TRAIL_0".extend(2);
      INSERT INTO "CONDPK"."AUDIT_TRAIL" ("DATA1")
      VALUES (:p0)
      RETURNING "ID" INTO "lAUDIT_TRAIL_0"(1)."ID";
      INSERT INTO "CONDPK"."AUDIT_TRAIL" ("DATA1")
      VALUES (:p1)
      RETURNING "ID" INTO "lAUDIT_TRAIL_0"(2)."ID";
      OPEN :cur1 FOR SELECT "lAUDIT_TRAIL_0"(1)."ID" FROM DUAL;
      OPEN :cur2 FOR SELECT "lAUDIT_TRAIL_0"(2)."ID" FROM DUAL;
      UPDATE "CONDPK"."V_SUBSCRIPTIONS" SET "VALID_TILL" = :p2
      WHERE "ID" = :p3
      RETURN "IS_ACTIVE" INTO v3_IS_ACTIVE;
      v_RowCount := SQL%ROWCOUNT;
      OPEN :cur3 FOR
      SELECT v3_IS_ACTIVE
      FROM DUAL
      WHERE v_RowCount = 1;

      INSERT INTO "CONDPK"."SUBSCRIPTION_ITEMS" ("ID", "SUBSCRIPTION_ID")
      VALUES (:p4, :p5);
      END;
fail: Microsoft.EntityFrameworkCore.Database.Command[0]
      2021-04-01 05:34:15.477928 ThreadID:1   (ERROR)   OracleModificationCommandBatch.Consume() :  System.InvalidCastException: Specified cast is not valid.
         at Oracle.ManagedDataAccess.Client.OracleDataReader.GetInt32(Int32 i)
         at Oracle.EntityFrameworkCore.Update.Internal.OracleModificationCommandBatch.Consume(RelationalDataReader relationalReader)
fail: Microsoft.EntityFrameworkCore.Infrastructure[0]
      2021-04-01 05:34:15.540603 ThreadID:1   (ERROR)   OracleExecutionStrategy.Execute() :  Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
       ---> System.InvalidCastException: Specified cast is not valid.
         at Oracle.ManagedDataAccess.Client.OracleDataReader.GetInt32(Int32 i)
         at Oracle.EntityFrameworkCore.Update.Internal.OracleModificationCommandBatch.Consume(RelationalDataReader relationalReader)
         --- End of inner exception stack trace ---
         at Oracle.EntityFrameworkCore.Update.Internal.OracleModificationCommandBatch.Consume(RelationalDataReader relationalReader)
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
         at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
         at Oracle.EntityFrameworkCore.Storage.Internal.OracleExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
fail: Microsoft.EntityFrameworkCore.Update[10000]
      An exception occurred in the database while saving changes for context type 'ConsoleApp3.MyDbContext'.
      Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
       ---> System.InvalidCastException: Specified cast is not valid.
         at Oracle.ManagedDataAccess.Client.OracleDataReader.GetInt32(Int32 i)
         at Oracle.EntityFrameworkCore.Update.Internal.OracleModificationCommandBatch.Consume(RelationalDataReader relationalReader)
         --- End of inner exception stack trace ---
         at Oracle.EntityFrameworkCore.Update.Internal.OracleModificationCommandBatch.Consume(RelationalDataReader relationalReader)
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection c

**Comment by alexkeh** [comment]
It's not clear what the root cause is from the EF Core trace. You are storing the SubscriptionItem entries as ints, which shouldn't cause any conversion issues. Perhaps we could discern more precise error info from the ODP.NET trace.

Can you provide the ODP.NET trace?

Add the following namespace:
`using Oracle.ManagedDataAccess.Client;
`
Then set the following values in your app before opening a connection:
`    OracleConfiguration.TraceFileLocation = @"<directory>";
    OracleConfiguration.TraceLevel = 7;`
