### ISSUE TITLE
NullReferenceException in Oracle.ManagedDataAccess.Client.OracleConnection.Close()

### ISSUE THREAD

**Issue by sungam3r** [oracle/dotnet-db-samples#165]
I noticed a suspicious error in our logs:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Oracle.ManagedDataAccess.Client.OracleConnection.Close()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Close()
```

We use Oracle.EntityFrameworkCore v3.19.80 and explicitly defined Oracle.ManagedDataAccess.Core v2.19.101 in our netcoreapp3.1 targeted app.

The output from `OracleConnection.Dump` after this happened, names have been replaced:
```
(DUMP)
(CP) =================================
(CP) Data Source=(DESCRIPTION=(ENABLE=BROKEN)(LOAD_BALANCE=off)(FAILOVER=on)
(TRANSPORT_CONNECT_TIMEOUT=10)(ADDRESS=(PROTOCOL=tcp)(HOST=<address1>)(PORT=1526))
(ADDRESS=(PROTOCOL=tcp)(HOST=<address2>)(PORT=1526))
(CONNECT_DATA=(SERVICE_NAME=<name>)(FAILOVER_MODE=(TYPE=session)(METHOD=basic))));
User Id=<id>;Password=;Connection Timeout=360;
(CP) pmid=
29168858(CP) =================================
(CP) <name> , <name2>:
(CP)   list  (count:34) : (1894:49713:T:F:F:F:N:<name>::<name2>)
(2336:53680:T:F:F:F:N:<name>::<name2>)
(2086:52739:T:F:F:F:N:<name>::<name2>)
(2525:57668:T:F:F:F:N:<name>::<name2>)
(2594:37744:T:F:F:F:N:<name>::<name2>)
(2781:59304:T:F:F:F:N:<name>::<name2>)
(73:2558:T:F:F:F:N:<name>::<name2>)
(1453:4436:F:F:T:F:N:<name>::<name2>)
(1836:53905:T:F:F:F:N:<name>::<name2>)
(2023:32936:F:F:T:F:N:<name>::<name2>)
(2530:39783:T:F:F:F:N:<name>::<name2>)
(4:32977:F:F:T:F:N:<name>::<name2>)
(449:60685:T:F:F:F:N:<name>::<name2>)
(509:18009:T:F:F:F:N:<name>::<name2>)
(575:19018:F:F:T:F:N:<name>::<name2>)
(951:24984:T:F:F:F:N:<name>::<name2>)
(1014:41852:F:F:T:F:N:<name>::<name2>)
(2147:11766:F:F:T:F:N:<name>::<name2>)
(2278:12919:F:F:T:F:N:<name>::<name2>)
(2845:40676:T:F:F:F:N:<name>::<name2>)
(67:43176:F:F:T:F:N:<name>::<name2>)
(388:56235:T:F:F:F:N:<name>::<name2>)
(445:35944:T:F:F:F:N:<name>::<name2>)
(1018:774:T:F:F:F:N:<name>::<name2>)
(1079:17282:T:F:F:F:N:<name>::<name2>)
(1207:49150:F:F:T:F:N:<name>::<name2>)
(1457:34856:T:F:F:F:N:<name>::<name2>)
(1640:27332:T:F:F:F:N:<name>::<name2>)
(1837:9988:F:F:T:F:N:<name>::<name2>)
(2027:62029:T:F:F:F:N:<name>::<name2>)
(2090:31195:F:F:T:F:N:<name>::<name2>)
(2215:49833:F:F:T:F:N:<name>::<name2>)
(2338:47201:T:F:F:F:N:<name>::<name2>)
(2405:49511:F:F:T:F:N:<name>::<name2>)

(CP)   queue (count:13) : 
(1837:9988:F:F:T:F:N:<name>::<name2>)
(2215:49833:F:F:T:F:N:<name>::<name2>)
(1453:4436:F:F:T:F:N:<name>::<name2>)
(1207:49150:F:F:T:F:N:<name>::<name2>)
(2278:12919:F:F:T:F:N:<name>::<name2>)
(67:43176:F:F:T:F:N:<name>::<name2>)
(2023:32936:F:F:T:F:N:<name>::<name2>)
(1014:41852:F:F:T:F:N:<name>::<name2>)
(4:32977:F:F:T:F:N:<name>::<name2>)
(2090:31195:F:F:T:F:N:<name>::<name2>)
(2147:11766:F:F:T:F:N:<name>::<name2>)
(575:19018:F:F:T:F:N:<name>::<name2>)
(2405:49511:F:F:T:F:N:<name>::<name2>)
```

**Comment by alexkeh** [comment]
The NRE error is a bit of a generic one. Can you provide the ODP.NET trace to understand where and what is in ODP.NET causing it? You can turn on ODP.NET tracing by using something like the following before you open a connection.

`OracleConfiguration.TraceFileLocation = @"D:\traces";
OracleConfiguration.TraceLevel = 7;`

**Comment by sungam3r** [comment]
> The NRE error is a bit of a generic one.

Yes, but at the same time it is rather strange to see it in such a method. This error occurred only once in the last 7 days. So turning on the trace will not give any effect.
