### ISSUE TITLE
Oracle.ManagedDataAccess.Client.OracleException (0x80004005): Connection request timed out

### ISSUE THREAD

**Issue by Nathan2020-0126** [oracle/dotnet-db-samples#171]
I can success get data from oracle when running in visual studio. but after I deployed to IIS, I always get error information like below.
I have tryed version with 2.19.101 and 2.19.80, but none of them worked.
`{
    "Error":{
        "Code":"Exception",
        "Message":"Connection request timed out",
        "Details":"Oracle.ManagedDataAccess.Client.OracleException (0x80004005): Connection request timed out
   at OracleInternal.ConnectionPool.PoolManager`3.Get(ConnectionString csWithDiffOrNewPwd, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)
   at OracleInternal.ConnectionPool.OraclePoolManager.Get(ConnectionString csWithNewPassword, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)
   at OracleInternal.ConnectionPool.OracleConnectionDispenser`3.Get(ConnectionString cs, PM conPM, ConnectionString pmCS, SecureString securedPassword, SecureString securedProxyPassword, OracleConnection connRefForCriteria)
   at Oracle.ManagedDataAccess.Client.OracleConnection.Open()
   at Serenity.Data.WrappedConnection.Open()
   at Serenity.Data.SqlConnections.EnsureOpen(IDbConnection connection)
   at Serenity.Data.SqlHelper.ExecuteScalar(IDbConnection connection, String commandText, IDictionary`2 param)
   at Serenity.Data.EntitySqlHelper.ForEach(SqlQuery query, IDbConnection connection, Action callBack)
   at Serenity.Services.ListRequestHandler`3.Process(IDbConnection connection, TListRequest request)
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.&lt;InvokeNextExceptionFilterAsync&gt;g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)"
    }
}
`

**Comment by alexkeh** [comment]
Can you increase the connection string Connection Timeout value to some high, such as 600 (i.e. ten minutes)? The default value is 15 seconds, which means it could be hit before the actual error you are hitting can trigger if it has a longer timeout value.

When you run the app again, the real problem's error should manifest itself and we should see it in the exception message.

**Comment by Nathan2020-0126** [comment]
I increated the timout value, now I got the new error.
`System.TypeLoadException:“Could not load type 'System.Security.Principal.WindowsImpersonationContext' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.”`

**Comment by alexkeh** [comment]
Two things to check:

1. Add the NuGet package System.Security,Principal to the IIS deployment if it's not there.
2. Make sure your deployed app uses ODP.NET Core or managed ODP.NET as intended. They share the same namespace and APIs, but they are two different assemblies. ODP.NET Core is for .NET Core/5 and managed ODP.NET is for .NET FW primarily. It looks like you are using .NET Core.

**Comment by Nathan2020-0126** [comment]
@alexkeh, thanks for your feedback, I checked two points.
1. System.Security.Principal.Windows.dll is there
![image](https://user-images.githubusercontent.com/16734387/119408046-a9775680-bd17-11eb-93bc-2c6a9af861f4.png)
2. Installed ODP.NetCore(version 2.0.12),before I was using Oracle.ManagedDataAccess.Core(version 3.21.1), but I got same error information
![image](https://user-images.githubusercontent.com/16734387/119410335-438cce00-bd1b-11eb-911a-b9d2aa2b12e6.png)

Error:
![image](https://user-images.githubusercontent.com/16734387/119410447-70d97c00-bd1b-11eb-84be-1eee1bd42107.png)

**Comment by alexkeh** [comment]
@Nathan2020-0126 I don't see the System.Security.Principal assembly. It's not the same assembly as System.Security.Principal.Windows. Can you try adding System.Security.Principal from NuGet Gallery?

**Comment by Nathan2020-0126** [comment]
I just installed the System.Security.Principal, still not work.
![image](https://user-images.githubusercontent.com/16734387/119423218-60ce9600-bd35-11eb-9383-1df452121ab3.png)

**Comment by alexkeh** [comment]
Looks like the [WindowsImpersonationContext class is only available in .NET FW](https://docs.microsoft.com/en-us/dotnet/api/system.security.principal.windowsimpersonationcontext?view=netframework-4.8&viewFallbackFrom=net-5.0). And you are using .NET Core.

Were there any configuration changes made between your VS configuration setup and IIS configuration setup, such as in how they use Active Directory usage? My guess is that Windows impersonation has been enabled in IIS.

**Comment by Nathan2020-0126** [comment]
I didnot change any configuration. and the windows impersonation is disabled
![image](https://user-images.githubusercontent.com/16734387/119955817-03577500-bfd3-11eb-82ed-d02ee0fc8d26.png)

**Comment by Nathan2020-0126** [comment]
I searched in githhub and find this page.
https://github.com/dotnet/runtime/issues/35389
WindowsImpersonationContext is not in .NET Core. It was an intentional decision since it has number of security problems. The discussion about this is at #20647 (comment)

**Comment by alexkeh** [comment]
Which .NET Core version are you using?

The ODP.NetCore package is not distributed by Oracle. It may include an assembly that Oracle distributed in the past, but we can't vouch for its authenticity because it was packaged by a third-party. Can you go back to use ODP.NET Core 3.21.1 package, which will work with .NET Core 3.1 and 5. If you need .NET Core 2.1 support, use the ODP.NET Core 2.19.110 version.

**Comment by Nathan2020-0126** [comment]
@alexkeh after I go back to use Oracle.ManagedDataAccess.Core version 3.21.1, the problem is solved. thanks very much

**Comment by alexkeh** [comment]
That's great!

**Comment by salahrzzaz** [comment]
https://github.com/oracle/dotnet-db-samples/issues/243

**Comment by AstorSkywalker** [comment]
Going **back to Oracle.ManagedDataAccess.Core version 3.21.1 was the answer**

**Comment by wortelus** [comment]
Going back to versions before 3.21.1 throws me an error of 
`Oracle.ManagedDataAccess.Client.OracleException: ORA-12514: TNS:listener does not currently know of service requested in connect descriptor`

even though i use connection string without the tnsnames.ora support. Otherwise I get conneection timeout..

**Comment by alexkeh** [comment]
@wortelus TNSNAMES is on by default unless you specifically enable alternative DB naming methods. You can turn on ODP.NET tracing to see what naming methods have been enabled, whether intended or unintended.

I suspect you likely have TNSNAMES enabled and ODP.NET has found a tnsnames.ora file somewhere, not necessarily in your current ODP.NET directory.
