### ISSUE TITLE
Specified cast is not valid.

### ISSUE THREAD

**Issue by HakanKaraoglu** [oracle/dotnet-db-samples#204]
Hi, I don't know if i should post the problem here but i wanted to try my luck :) please guide me

I have a method as below. However, this method gives the error I have stated below in some queries. So sometimes it works fine, sometimes it doesn't. I couldn't come up with an idea about the cause. Can you help me ?

```
public async Task<FeedDetail> GetFeedDetailByFeedAsync(Feed feed)
        {
            var query = await _session.CreateCriteria<FeedDetail>()
                                 .Add(Restrictions.Eq("Feed", feed))
                                 .Add(Restrictions.Eq("IsActive", true))
                                 .SetFetchMode("Feeder", FetchMode.Eager)
                                 .SetFetchMode("Feed", FetchMode.Eager)
                                 .SetFetchMode("Workspace", FetchMode.Eager)
                                 .SetFetchMode("Source", FetchMode.Eager)
                                 .SetMaxResults(1).UniqueResultAsync<FeedDetail>();

            return query;
        }
```

```
at Oracle.ManagedDataAccess.Client.OracleDataReader.GetDecimal(Int32 i)
at Oracle.ManagedDataAccess.Client.OracleDataReader.GetValue(Int32 i)
at NHibernate.Type.NullableType.NullSafeGet(DbDataReader rs, String name, ISessionImplementor session)
at NHibernate.Type.NullableType.NullSafeGetAsync(DbDataReader rs, String[] names, ISessionImplementor session, Object owner, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
at NHibernate.Persister.Entity.AbstractEntityPersister.HydrateAsync(DbDataReader rs, Object id, Object obj, String[][] suffixedPropertyColumns, ISet`1 fetchedLazyProperties, Boolean allProperties, Int32[] indexes, ISessionImplementor session, CancellationToken cancellationToken)
at NHibernate.Loader.Loader.LoadFromResultSetAsync(DbDataReader rs, Int32 i, Object obj, ILoadable persister, EntityKey key, LockMode lockMode, ILoadable rootPersister, ISessionImplementor session, CancellationToken cancellationToken)
at NHibernate.Loader.Loader.InstanceNotYetLoadedAsync(DbDataReader dr, Int32 i, ILoadable persister, EntityKey key, LockMode lockMode, EntityKey optionalObjectKey, Object optionalObject, IList hydratedObjects, ISessionImplementor session, CancellationToken cancellationToken)
at NHibernate.Loader.Loader.GetRowAsync(DbDataReader rs, ILoadable[] persisters, EntityKey[] keys, Object optionalObject, EntityKey optionalObjectKey, LockMode[] lockModes, IList hydratedObjects, ISessionImplementor session, Boolean mustLoadMissingEntity, Action`2 cacheBatchingHandler, CancellationToken cancellationToken)
at NHibernate.Loader.Loader.GetRowFromResultSetAsync(DbDataReader resultSet, ISessionImplementor session, QueryParameters queryParameters, LockMode[] lockModeArray, EntityKey optionalObjectKey, IList hydratedObjects, EntityKey[] keys, Boolean returnProxies, IResultTransformer forcedResultTransformer, QueryCacheResultBuilder queryCacheResultBuilder, Action`2 cacheBatchingHandler, CancellationToken cancellationToken)
at NHibernate.Loader.Loader.DoQueryAsync(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer, QueryCacheResultBuilder queryCacheResultBuilder, CancellationToken cancellationToken)
at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollectionsAsync(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer, QueryCacheResultBuilder queryCacheResultBuilder, CancellationToken cancellationToken)
at NHibernate.Loader.Loader.DoListAsync(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer, QueryCacheResultBuilder queryCacheResultBuilder, CancellationToken cancellationToken)
```

The response I got from the group using Nhibernate is that it's an oracle bug.

"There is a lot of possible causes with this issue. First, this seems to be an Oracle issue, calling for an Oracle fix, not a NHibernate one. And maybe your case can be fixed, I do not know. You have to analyze it thoroughly, checking your used types, whether you should use Oracle binary_double or some other type for your columns, whether Oracle setting for avoiding this exception is of any help in your case"

**Comment by alexkeh** [comment]
Which managed ODP.NET version are you using and does the error occur when the numbers retrieved are a certain size?

One possible reason the error occurs is that the number retrieved is larger than 28 precision. .NET Decimals support up to 28 precision whereas Oracle NUMBERs can support up to 38 precision.

**Comment by HakanKaraoglu** [comment]
> Which managed ODP.NET version are you using and does the error occur when the numbers retrieved are a certain size?
> 
> One possible reason the error occurs is that the number retrieved is larger than 28 precision. .NET Decimals support up to 28 precision whereas Oracle NUMBERs can support up to 38 precision.

I am using Nhibernate with Oracle.ManagedDataAccess.Core v3.21.1, actually there is no decimal variable in the model, some fields are of type double.The interesting thing is that sometimes it works and sometimes it doesn't.

**Comment by alexkeh** [comment]
If the data types are doubles, you should call GetDouble instead of GetDecimal. That's likely why you get the specified cast is invalid error.

I'm not familiar with the inner workings of NHibernate. Is there a way to control which getter to use based on the data type?

**Comment by HakanKaraoglu** [comment]
Actually my query is like this. That is, I am not sending a decimal or double variable. This is the Nhibernate model configuration. It doesn't matter if it's Nhibernate or not, I'm just trying to figure out why

Our model structure is below (I shortened it a little so that it wouldn't be long, the original is longer), both models are connected with Feed type, there is a query produced by NH at the bottom, I run the query, oracle is running, there is no error, I can see the output. However, as you can see in the above query, I'm just giving the feed object as a variable. But I'm trying to understand the cause of such a problem.

```
 session.CreateCriteria<FeedDetail>()
                                 .Add(Restrictions.Eq("Feed", feed))
                                 .Add(Restrictions.Eq("IsActive", true))
                                 .SetFetchMode("Feeder", FetchMode.Eager)
                                 .SetFetchMode("Feed", FetchMode.Eager)
                                 .SetFetchMode("Workspace", FetchMode.Eager)
                                 .SetFetchMode("Source", FetchMode.Eager)
                                 .SetMaxResults(1).UniqueResultAsync<FeedDetail>();
```

```
 public class FeedDetail : EntityBase<long>
    {
        public virtual string Body { get; set; }
        public virtual string BodyHtml { get; set; }
        public virtual string Caption { get; set; }
        public virtual double? GeoLat { get; set; }
        public virtual double? GeoLong { get; set; }
        public virtual string ChannelKey { get; set; }
        public virtual Feed Feed { get; set; }
        public virtual double? Klout { get; set; }
    }

References(x => x.Feed).Column("DOCID").LazyLoad();

public class Feed : EntityBase<long>
    {
        public virtual Feed Parent { get; set; }
        public virtual string FeedId { get; set; }
        public virtual DateTime FeedDate { get; set; }
        public virtual string FeedType { get; set; }
        public virtual string Title { get; set; }
        public virtual Source Source { get; set; }
 }


        
SELECT id1_12_3_,
       isactive2_12_3_,
       createuser3_12_3_,
       createtime4_12_3_,
       updateuser5_12_3_,
       updatetime6_12_3_,
       body7_12_3_,
       bodyhtml8_12_3_,
       caption9_12_3_,      
       weight13_38_1_,
       id1_30_2_,
       isactive2_30_2_,
       createuser3_30_2_,
       createtime4_30_2_,
       updateuser5_30_2_,
       updatetime6_30_2_,
       name7_30_2_,
       genericpublisher8_30_2_,
       datasiftcode9_30_2_,
       sourcetype10_30_2_
FROM   (SELECT this_.id                   AS id1_12_3_,
               this_.isactive             AS isactive2_12_3_,
               this_.createuser           AS createuser3_12_3_,
               this_.createtime           AS createtime4_12_3_,
               this_.updateuser           AS updateuser5_12_3_,
               this_.updatetime           AS updatetime6_12_3_,
               this_.BODY                 AS body7_12_3_,               
               this_.nerperson            AS nerperson42_12_3_,                
               this_.sourceid             AS sourceid49_12_3_,
               feed2_.id                  AS id1_15_0_,
               feed2_.isactive            AS isactive2_15_0_,
               feed2_.createuser          AS createuser3_15_0_,
               feed2_.createtime          AS createtime4_15_0_,
               feed2_.opstatusid          AS opstatusid65_15_0_,
               workspace3_.id             AS id1_38_1_,
               workspace3_.isactive       AS isactive2_38_1_,
               workspace3_.createuser     AS createuser3_38_1_,               
               workspace3_.workspacegroup AS workspacegroup11_38_1_,
               workspace3_.ismobileactive AS ismobileactive12_38_1_,
               workspace3_.weight         AS weight13_38_1_,
               source4_.id                AS id1_30_2_,
               source4_.isactive          AS isactive2_30_2_,
               source4_.sourcetype        AS sourcetype10_30_2_
        FROM   social_feed_detail this_
               left outer join social_feed feed2_
                            ON this_.docid = feed2_.id
               left outer join social_workspace workspace3_
                            ON this_.workspaceid = workspace3_.id
               left outer join social_source source4_
                            ON this_.sourceid = source4_.id
        WHERE  this_.docid = 440757347
               AND this_.isactive = 1)
WHERE  ROWNUM <= 1 

```

**Comment by HakanKaraoglu** [comment]
I think I found the problem,

As you said, the double field has a very long value (some bad records have this problem), I didn't notice it, it's my fault. where it works, it probably applies to null or lower value typed data.
