### ISSUE TITLE
.Net Core Oracle Connection time out

### ISSUE THREAD

**Issue by salahrzzaz** [oracle/dotnet-db-samples#243]
we have application .net core with oracle database published since 8 months unexpectedly returned request connection time and we didn't make any deployment and we didn't use it much time because we are waiting for phase 2

**.Net Core 5 Packages version**

- Microsoft.EntityFrameworkCore >> 5.0.17
- Oracle.ManagedDataAccess.Client >> 3.21.61
- Oracle.EntityFrameworkCore >> 5.21.61

**### we tried the following:**

- Restart IIS
- restart the app server
- restart the database server
- increase the time out in the connection string
- increase min & max pool size
- I tried Dapper and gave the same error
- I created the small app with one DB set (table) and deployed it on
- the server it is worked successfully on the same database and same server
- telnet on the database server from the server and worked

### **Some Notes:**

the application always now gave request connection time on the production server.
the application works with the same database on the visual studio on my machine.
and also I deployed the app on my machine and worked
the Issue is only on production servers
we access the database from local machine using VPN

**the log below:**

{ "time": "2022-05-13 00:28:40.8846", "level": "ERROR(Microsoft.EntityFrameworkCore.Database.Connection)", "url": "http://dedportal.uaqgov.ae/api/Activity/ActivityListAll", "actionName": "ActivityListAll", "Message": "An error occurred using the connection to database '' on server host/service name'." },

{ "time": "2022-05-13 00:28:40.9270", "level": "ERROR(Microsoft.EntityFrameworkCore.Infrastructure)", "url": "http://dedportal.uaqgov.ae/api/Activity/ActivityListAll", "actionName": "ActivityListAll", "Message": "1443-10-12 00:28:40.923393 ThreadID:4 (ERROR) OracleExecutionStrategy.ExecuteAsync() : Oracle.ManagedDataAccess.Client.OracleException (0x80004005): Connection request timed out\r\n at OracleInternal.ConnectionPool.PoolManager3.Get(ConnectionString csWithDiffOrNewPwd, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)\r\n   at OracleInternal.ConnectionPool.OraclePoolManager.Get(ConnectionString csWithNewPassword, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)\r\n   at OracleInternal.ConnectionPool.OracleConnectionDispenser3.Get(ConnectionString cs, PM conPM, ConnectionString pmCS, SecureString securedPassword, SecureString securedProxyPassword, OracleConnection connRefForCriteria)\r\n at Oracle.ManagedDataAccess.Client.OracleConnection.Open()\r\n at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)\r\n--- End of stack trace from previous location ---\r\n at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)\r\n at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)\r\n at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)\r\n at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)\r\n at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)\r\n   at Oracle.EntityFrameworkCore.Storage.Internal.OracleExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)" },

{ "time": "2022-05-13 00:28:40.9660", "level": "ERROR(Microsoft.EntityFrameworkCore.Query)", "url": "http://dedportal.uaqgov.ae/api/Activity/ActivityListAll", "actionName": "ActivityListAll", "ExceptionType": "Oracle.ManagedDataAccess.Client.OracleException", "ExceptionMessage": "Connection request timed out", "StackTrace": " at OracleInternal.ConnectionPool.PoolManager3.Get(ConnectionString csWithDiffOrNewPwd, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)\r\n   at OracleInternal.ConnectionPool.OraclePoolManager.Get(ConnectionString csWithNewPassword, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)\r\n   at OracleInternal.ConnectionPool.OracleConnectionDispenser3.Get(ConnectionString cs, PM conPM, ConnectionString pmCS, SecureString securedPassword, SecureString securedProxyPassword, OracleConnection connRefForCriteria)\r\n at Oracle.ManagedDataAccess.Client.OracleConnection.Open()\r\n at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)\r\n--- End of stack trace from previous location ---\r\n at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)\r\n at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)\r\n at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)\r\n at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)\r\n at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)\r\n   at Oracle.EntityFrameworkCore.Storage.Internal.OracleExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func4 operation, Func4 verifySucceeded, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable1.AsyncEnumerator.MoveNextAsync()", "Message": "An exception occurred while iterating over the results of a query for context type 'UAQDED.Infrastructure.DB.DBContext.ModelContext'.\r\nOracle.ManagedDataAccess.Client.OracleException (0x80004005): Connection request timed out\r\n at OracleInternal.ConnectionPool.PoolManager3.Get(ConnectionString csWithDiffOrNewPwd, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)\r\n   at OracleInternal.ConnectionPool.OraclePoolManager.Get(ConnectionString csWithNewPassword, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)\r\n   at OracleInternal.ConnectionPool.OracleConnectionDispenser3.Get(ConnectionString cs, PM conPM, ConnectionString pmCS, SecureString securedPassword, SecureString securedProxyPassword, OracleConnection connRefForCriteria)\r\n at Oracle.ManagedDataAccess.Client.OracleConnection.Open()\r\n at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)\r\n--- End of stack trace from previous location ---\r\n at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)\r\n at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)\r\n at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)\r\n at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)\r\n at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)\r\n   at Oracle.EntityFrameworkCore.Storage.Internal.OracleExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func4 operation, Func4 verifySucceeded, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable1.AsyncEnumerator.MoveNextAsync()" },

**Comment by alexkeh** [comment]
If the problem only occurs between the production app and production DB servers, but works fine everywhere else, then I suspect there's some configuration issue between the production setup causing the problem. Do you have a load balancer or firewall between IIS and the DB? If so, does it have a TCP idle timeout set that is killing connections in the pool that are not being used after a certain amount of time? Many cloud PaaS have a default TCP idle timeout setup.

It would be helpful if you could establish a pattern the determines when you see connection timeouts.

**Comment by salahrzzaz** [comment]
yes, we have a load balancer on the database level and on the app level but regrading the app load balancer we already stop one of them. but I didn't have administrator access to the database I will contact DBA

**Comment by salahrzzaz** [comment]
we tried and not working anyone can help

**Comment by alexkeh** [comment]
Is there a pattern to when and which connections get a timeout? 

Anything in your configuration that could be killing connections/network connectivity?

**Comment by salahrzzaz** [comment]
always any API connecting to database gave timeout the connection string :

User Id=<uer id>;Password=<Password>;Data Source=Host:1546/servicename

**Comment by alexkeh** [comment]
If it's all the time, try increasing your connection timeout to something like 300 seconds. Some errors don't manifest themselves until after the default 15 second connection timeout, such as wallet errors.

**Comment by salahrzzaz** [comment]
i added this to the connection string:  Connection Timeout=600 and still the same

**Comment by alexkeh** [comment]
You can turn on ODP.NET tracing to see where in the connection process the timeout occurs. My guess is that there's some place the process gets hung. It should error out, but the trace will tell us where it's stuck.

Can any other machine access the production DB? Can SQL Plus, SQL Developer or JDBC to access the production DB?

**Comment by salahrzzaz** [comment]
Yes SQL developer connected to the database from production server

**Comment by alexkeh** [comment]
Are SQL Developer and ODP.NET using the same port to connect to Oracle DB?

The root cause analysis can be more productive if you can get an ODP.NET trace. Otherwise, we'll have to experiment with each area of the networking process one at a time. IT can be especially hard for someone outside your organization to drive the investigation, then we'll need to tackle each possible area one at a time since they won't have any knowledge of your network stack and environment.

Another option is to open up an Oracle Support service request to investigate. Some companies are sensitive posting their software stack publicly, especially trace information, which are very detailed.

**Comment by salahrzzaz** [comment]
Yes, SQL Developer access with the same port,
Can you share any tutorial about ODP.NET trace?

What is the information you want and I can share it with you?

**Comment by salahrzzaz** [comment]
Here is trace file output :



1443-10-13 22:30:34.731422 TID:6   (CFG) (ENV)      Machine Name : U01VPFESDED01
1443-10-13 22:30:34.733843 TID:6   (CFG) (ENV)      User Name : dotnet6
1443-10-13 22:30:34.734082 TID:6   (CFG) (ENV)      OS Version : Microsoft Windows NT 10.0.14393.0
1443-10-13 22:30:34.734158 TID:6   (CFG) (ENV)      64-bit OS : True
1443-10-13 22:30:34.734210 TID:6   (CFG) (ENV)      64-bit Process : True
1443-10-13 22:30:34.734326 TID:6   (CFG) (ENV)      .NET Core Runtime Version : 6.0.5
1443-10-13 22:30:34.734381 TID:6   (CFG) (ENV)      Application Directory : E:\DED\UAQ-DED\test3
1443-10-13 22:30:34.734472 TID:6   (CFG) (VER)      Oracle Data Provider for .NET Core Driver Version : 3.1.21.1
1443-10-13 22:30:34.740301 TID:6   (CFG) (VER)      Oracle Data Provider for .NET Core Driver Informational Version : 3.1.21.1:20220416
1443-10-13 22:30:34.740506 TID:6   (CFG) (.NET)     disable_oob : True
1443-10-13 22:30:34.740583 TID:6   (CFG) (.NET)     send_buf_size : 8192
1443-10-13 22:30:34.740607 TID:6   (CFG) (.NET)     recv_buf_size : 8192
1443-10-13 22:30:34.747407 TID:6   (CFG) (SQLNET)   FilePath : (null)
1443-10-13 22:30:34.747483 TID:6   (CFG) (TNSNAMES) FilePath : (null)
1443-10-13 22:30:34.768311 TID:6   (CFG) (OCFG)     OracleConfiguration.DumpInfo()  TraceFileLocation : E:\traces
 TraceLevel : 7
 TraceOption : 1
 CommandTimeout : 60
 BindByName : True
 FetchSize : 1048576
 SelfTuning : False
 StatementCacheSize : 25
 DisableOOB : True
 SendBufferSize : 8192
 ReceiveBufferSize : 8192
 OracleDataSources : orcl : (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=<hostname or IP>)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=<service name>)(SERVER=dedicated)))
 OracleDataSources : orclpdb : (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=<hostname or IP>)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=<service name>)(SERVER=dedicated)))

1443-10-13 22:30:34.718667 TID:6   (PUB) (ENT) OracleConnection.Open() (conid=40251712) (state=Closed) (sessid=0) (implid=0) (pooling=T) (txnid=n/a) 
1443-10-13 22:30:34.772850 TID:6   (PRI) (ENT) (CP) OracleConnectionDispenser..cctor()
1443-10-13 22:30:34.774438 TID:6   (PRI) (EXT) (CP) OracleConnectionDispenser..cctor()
1443-10-13 22:30:34.774520 TID:6   (PRI) (ENT) (CP) OracleConnectionDispenser.Get()
1443-10-13 22:30:34.780086 TID:6   (PRI) (ENT) (CP) PoolManager.ctor()
1443-10-13 22:30:34.782404 TID:6   (PRI) (EXT) (CP) PoolManager.ctor()
1443-10-13 22:30:34.785017 TID:6   (PRI) (ENT) (CP) PoolManager.Initialize() <Connection string>
1443-10-13 22:30:34.786326 TID:6   (PRI) (EXT) (CP) PoolManager.Initialize() (pmid=26448968)  <Connection string>
1443-10-13 22:30:34.792301 TID:6   (PRI) (BUF) (OBP.CTOR) (poolid:28822586) (OracleConnectionDispenser`3.GetPM)
1443-10-13 22:30:34.800356 TID:6   (PRI) (ENT) (CP) OraclePoolManager.Get()
1443-10-13 22:30:34.872643 TID:6   (PRI) (ENT) (CP) PoolManager.Get() (txnid=n/a) (bForceMatch=F)
1443-10-13 22:30:34.873620 TID:6   (PRI) (ENT) (CP) PoolManager.Get() MultiTenant : Searching for a idle connection, retryCountWithoutAffinity: 0
1443-10-13 22:30:34.874608 TID:6   (PRI) (ENT) PoolManager.ProcessCriteriaCtx_NonEnlistedConnection()
1443-10-13 22:30:34.874683 TID:6   (PRI) (EXT) PoolManager.ProcessCriteriaCtx_NonEnlistedConnection()
1443-10-13 22:30:34.891761 TID:6   (PRI) (ENT) (CP) PoolManager.CreateNewPR() (txnid=n/a) 
1443-10-13 22:30:34.893683 TID:6   (PRI) (ENT) (CP) PoolManager.CreateNewPR() Connecting with session time zone as the Region name
1443-10-13 22:30:49.920425 TID:6   (PRI) (CP) PoolManager.CreateNewPR() (DUMP)
(CP) =================================
(CP) <connection string>
(CP) pmid=
26448968(CP) =================================

1443-10-13 22:30:49.921913 TID:6   (PRI) (ENT) OracleException.ctor()
1443-10-13 22:30:49.922787 TID:6   (PRI) (ENT) OracleError.ctor()
1443-10-13 22:30:49.929919 TID:6   (PRI) (EXT) OracleError.ctor()
1443-10-13 22:30:49.929992 TID:6   (PRI) (ENT) OracleError.ctor()
1443-10-13 22:30:49.930032 TID:6   (PRI) (EXT) OracleError.ctor()
1443-10-13 22:30:49.930062 TID:6   (PRI) (EXT) OracleException.ctor()
1443-10-13 22:30:49.931762 TID:6   (PRI) (ENT) PoolManager.CreateNewPR()
1443-10-13 22:30:49.954609 TID:6   (PRI) (ERR) (CP) PoolManager.CreateNewPR() (txnid=n/a) Oracle.ManagedDataAccess.Client.OracleException (0x80004005): Connection request timed out
   at OracleInternal.ConnectionPool.PoolManager`3.CreateNewPR(Int32 reqCount, Boolean bForPoolPopulation, ConnectionString csWithDiffOrNewPwd, OracleConnection connRefForCriteria, String instanceName, List`1 switchFailedInstNames)
1443-10-13 22:30:49.954716 TID:6   (PRI) (EXT) PoolManager.CreateNewPR()
1443-10-13 22:30:49.955217 TID:6   (PRI) (EXT) (CP) PoolManager.CreateNewPR() (aff=n/a) (inst=) (affmatch=n/a) (pr.service=) (pr.pdb=) (pr.edition=) (sessid=-1:-1) (F;F;F;;N) (pmid=26448968) 
1443-10-13 22:30:49.955402 TID:6   (PRI) (EXT) (CP) PoolManager.Get() (txnid=n/a) PM.Get(aff=;force=F) returning (null)
1443-10-13 22:30:49.955455 TID:6   (PRI) (ENT) OraclePoolManager.Get()
1443-10-13 22:30:49.956211 TID:6   (PRI) (ERR) (CP) OraclePoolManager.Get() (txnid=n/a) Oracle.ManagedDataAccess.Client.OracleException (0x80004005): Connection request timed out
   at OracleInternal.ConnectionPool.PoolManager`3.Get(ConnectionString csWithDiffOrNewPwd, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)
   at OracleInternal.ConnectionPool.OraclePoolManager.Get(ConnectionString csWithNewPassword, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)
1443-10-13 22:30:49.956310 TID:6   (PRI) (EXT) OraclePoolManager.Get()
1443-10-13 22:30:49.956427 TID:6   (PRI) (EXT) (CP) OraclePoolManager.Get() (txnid=n/a) 
1443-10-13 22:30:49.958571 TID:6   (PRI) (ENT) OracleConnectionDispenser.Get()
1443-10-13 22:30:49.958925 TID:6   (PRI) (ERR) (CP) OracleConnectionDispenser.Get() (txnid=n/a) Oracle.ManagedDataAccess.Client.OracleException (0x80004005): Connection request timed out
   at OracleInternal.ConnectionPool.PoolManager`3.Get(ConnectionString csWithDiffOrNewPwd, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)
   at OracleInternal.ConnectionPool.OraclePoolManager.Get(ConnectionString csWithNewPassword, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)
   at OracleInternal.ConnectionPool.OracleConnectionDispenser`3.Get(ConnectionString cs, PM conPM, ConnectionString pmCS, SecureString securedPassword, SecureString securedProxyPassword, OracleConnection connRefForCriteria)
1443-10-13 22:30:49.958989 TID:6   (PRI) (EXT) OracleConnectionDispenser.Get()
1443-10-13 22:30:49.959093 TID:6   (PRI) (EXT) (CP) OracleConnectionDispenser.Get() (txnid=n/a) 
1443-10-13 22:30:49.959140 TID:6   (PRI) (ENT) OracleConnection.Open()
1443-10-13 22:30:49.959338 TID:6   (PUB) (ERR) OracleConnection.Open() (txnid=n/a) Oracle.ManagedDataAccess.Client.OracleException (0x80004005): Connection request timed out
   at OracleInternal.ConnectionPool.PoolManager`3.Get(ConnectionString csWithDiffOrNewPwd, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)
   at OracleInternal.ConnectionPool.OraclePoolManager.Get(ConnectionString csWithNewPassword, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)
   at OracleInternal.ConnectionPool.OracleConnectionDispenser`3.Get(ConnectionString cs, PM conPM, ConnectionString pmCS, SecureString securedPassword, SecureString securedProxyPassword, OracleConnection connRefForCriteria)
   at Oracle.ManagedDataAccess.Client.OracleConnection.Open()
1443-10-13 22:30:49.959388 TID:6   (PRI) (EXT) OracleConnection.Open()
1443-10-13 22:30:49.959511 TID:6   (PUB) (EXT) OracleConnection.Open() (conid=40251712) (state=Closed) (sessid=0) (implid=0) (pooling=T) (txnid=n/a) 
1443-10-13 22:30:49.972986 TID:6   (PUB) (ENT) OracleConnection.Dispose()
1443-10-13 22:30:49.973140 TID:6   (PUB) (EXT) OracleConnection.Dispose()

**Comment by alexkeh** [comment]
Can you increase the connection timeout value back to 300 or above? The connection times out at 15 seconds. It's hard to see how far the connection attempt can reach internally. Also, is this the full trace? There seems to be some missing info that the trace would normally output.

**Comment by salahrzzaz** [comment]
Here are all files after increasing connection timeout =300 and  maxRetryCount = 3, maxRetryDelay = 90s

https://drive.google.com/drive/folders/1gd-VVJziosQth1EPxs7fiD5UPw58sLLM?usp=sharing

**Comment by alexkeh** [comment]
This looks like Bug 32171564. I'll confirm with the dev team next week.

**Comment by salahrzzaz** [comment]
Can you share the other bug link ? (32171564)

**Comment by alexkeh** [comment]
The bug would be only available for those with [My Oracle Support (MOS)](https://support.oracle.com/) accounts. Your DBA should have access to it.

Right now, the bug is non-public to MOS account holders since it was first found via internal testing. Internal bugs are not always guaranteed to have been part of a production release. When we confirm a customer has hit an existing bug externally, we usually then make it public.

**Comment by salahrzzaz** [comment]
We solved this it seems that our scan listeners have an issue I used the IP of the database nodes and it is working.

Thank you so much

**Comment by alexkeh** [comment]
That's good to hear.

**Comment by ronnyek** [comment]
I'm not necessarily trying to get this reopened... but I'm experiencing the same exceptions happening in the same place when app is under load and starts experiencing parallelism (oracle.manageddataaccess.core 2.19.110). In digging in, it seems like connection pool just starts bogging down bigtime, and ultimately after a point... we get nothing but connection timeouts. 

While we're in this state where our web application is trying to get a new open connection from the pool, iis becomes unresponsive and begins to consume very high level of cpu.

We've profiled a unit test that demonstrates this by trying to get ~25 simultaneous connections executing 100 queries in a row as fast as they can (open connection, execute query, dispose connection). The result of the profile appears to show that a great deal of the total execution time in `PoolManager.Get`, `OracleTuner.TuningFunction`, and `PoolManager.CreateNewPR`

![image](https://user-images.githubusercontent.com/584713/169296004-f81924f7-30b7-4b5b-97bb-76992641e3c3.png)

The weirdest problem here is that I've built tests that specifically avoid the wrapper library (linq2db) and simulated load seems to be fine and work as expected, but when this library is in place, this problem is far less prevalent... but profiles still show the majority of the time for everywhing is spent in just trying to open a new connection.

**Comment by alexkeh** [comment]
The timeout exception just means that the connection couldn't open in time. before the timeout hit There are many possible root causes. 

If you are trying top open 25 connections all at once and haven't warmed up the pool to have 25 connections ready to dispense, that could be one big source of a slowdown.

**Comment by ronnyek** [comment]
So I dispose of the connection... but I set max pool size of 100, and a timeout of 60 seconds. I launched 120 threads all executing a query that normally executes very very quickly (.052s) and then dispose of the connection. 100 queries appear to succeed, and then get connection timeouts for the remaining 20 connections. 

Is there additional information I can capture about the health of a connection pool (properties or something I can hit on an oracleconnection to see if of the 100 total connections 100 are full)?

Is there some amount of time that it takes for a connection after being disposed to be returned for the connection pool for re-use?

**Comment by alexkeh** [comment]
You can use ODP.NET connection pool counters to monitor pool health. You can [read more](https://docs.oracle.com/en/database/oracle/oracle-database/21/odpnt/featConnecting.html#GUID-4FA1C8D3-195B-4D7A-9E9D-9FB74C7F5312) or [watch a video](https://www.youtube.com/watch?v=mNwaYIazxlw) on setting them up.

If there a free connections available and a connection times out, then that's a definite problem.

They only work on Windows since they use System.Diagnostics. Typically, PerfMon is used to monitor these counters graphically.

The counters can answer the question of what is happening, but not so much the why. Turning on ODP.NET tracing can better inform the why.
