### ISSUE TITLE
Migration changing type of column: NVARCHAR2(2000 CHAR) -> CLOB emmits bad non running code which throws

### ISSUE THREAD

**Issue by ChaosEngine** [oracle/dotnet-db-samples#262]
This is somewhat similar to https://github.com/oracle/dotnet-db-samples/issues/256
For table described as:
```
  CREATE TABLE "DOTNET_TST"."GoogleProtectionKeys" 
   (	"Id" NVARCHAR2(450) NOT NULL ENABLE, 
	"Json" NVARCHAR2(2000), 
	"Environment" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PK_GoogleProtectionKeys" PRIMARY KEY ("Id")
);
```
and EF Core context looks (roughly) like this:
```
modelBuilder.Entity("DotnetPlayground.Models.GoogleProtectionKey", b =>
 {
       b.Property<string>("Id");
       b.Property<string>("Environment");
       b.Property<string>("Json");
       b.HasKey("Id", "Environment");
       b.ToTable("GoogleProtectionKeys");
});
```

Now, when running migration described by:
```
migrationBuilder.AlterColumn<string>(
    name: "Json",
    table: "GoogleProtectionKeys",
    type: "CLOB",
    nullable: true,
    oldType: "varchar(100)");
```
which extends lenfth of Json column to be clob (we'll be holding biiiggger json content inside)
I see this underlying PLSQL emmited:
```
declare
   l_nullable user_tab_columns.nullable % type;
begin 
   select nullable into l_nullable 
   from user_tab_columns 
  where table_name = 'GoogleProtectionKeys' 
  and column_name = 'Json' 
;
   if l_nullable = 'N' then 
        EXECUTE IMMEDIATE 'ALTER TABLE "GoogleProtectionKeys" MODIFY "Json" CLOB NULL';
 else 
        EXECUTE IMMEDIATE 'ALTER TABLE "GoogleProtectionKeys" MODIFY "Json" CLOB';
 end if;
end;
```

Unfortunatelly this code throws exception on applying migration (fresh db created from scratch):
```
Microsoft.EntityFrameworkCore.Database.Command: Error: 2022-11-04 21:49:19.548946 ThreadID:1   (ERROR)   OracleRelationalCommand.ExecuteNonQueryAsync() :  Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-22858: niepoprawna zmiana typu danych
ORA-06512: przy linia 12
   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, OracleConnection connection, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()
   at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (390ms) [Parameters=[], CommandType='Text', CommandTimeout='0']
      declare
         l_nullable user_tab_columns.nullable % type;
      begin
         select nullable into l_nullable
         from user_tab_columns
        where table_name = 'GoogleProtectionKeys'
        and column_name = 'Json'
      ;
         if l_nullable = 'N' then
              EXECUTE IMMEDIATE 'ALTER TABLE "GoogleProtectionKeys" MODIFY "Json" CLOB NULL';
       else
              EXECUTE IMMEDIATE 'ALTER TABLE "GoogleProtectionKeys" MODIFY "Json" CLOB';
       end if;
      end;
Microsoft.EntityFrameworkCore.Database.Command: Error: Failed executing DbCommand (390ms) [Parameters=[], CommandType='Text', CommandTimeout='0']
declare
   l_nullable user_tab_columns.nullable % type;
begin 
   select nullable into l_nullable 
   from user_tab_columns 
  where table_name = 'GoogleProtectionKeys' 
  and column_name = 'Json' 
;
   if l_nullable = 'N' then 
        EXECUTE IMMEDIATE 'ALTER TABLE "GoogleProtectionKeys" MODIFY "Json" CLOB NULL';
 else 
        EXECUTE IMMEDIATE 'ALTER TABLE "GoogleProtectionKeys" MODIFY "Json" CLOB';
 end if;
end;
Exception thrown: 'Oracle.ManagedDataAccess.Client.OracleException' in System.Private.CoreLib.dll
Exception thrown: 'Oracle.ManagedDataAccess.Client.OracleException' in System.Private.CoreLib.dll
Unhandled exception. Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-22858: niepoprawna zmiana typu danych
ORA-06512: przy linia 12
   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, OracleConnection connection, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()
   at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
   at DotnetPlayground.ContextFactory.CreateDBApplyMigrationsAndSeedDebugUsers(IHost host, CancellationToken token) in C:\Users\apauli\source\repos\ChaosEngine\Dotnet-Playground\DotnetPlayground.Web\Helpers\ContextFactory.cs:line 247
   at DotnetPlayground.Startup.Main(String[] args) in C:\Users\apauli\source\repos\ChaosEngine\Dotnet-Playground\DotnetPlayground.Web\Startup.cs:line 128
   at DotnetPlayground.Startup.<Main>(String[] args)
The program '[14916] DotnetPlayground.Web.dll' has exited with code 0 (0x0).
```

Interesting bits are: `ORA-22858: invalid alteration of datatype
ORA-06512: by line 12

**Comment by ChaosEngine** [comment]
Possibly this has to be implement with some create temp-column-hackery shown [here](https://asktom.oracle.com/pls/apex/f?p=100:11:108012884600548:::::)

**Comment by alexkeh** [comment]
Can you first migrate NVARCHAR2 to a LONG column, then conduct a conversion of the LONG column to CLOB? That's one workaround for a generic VARCHAR2 to CLOB conversion.

**Comment by ChaosEngine** [comment]
Yeah, I saw that option also, but went with converting to simpler varchar2(4000). My size requirements are (hopefully) not so demanding and that should suffice.
But this could be still a problem in other cases and EF Core migration is not properly generated here. Other DB providers are also lacking in this area so :-/
