### ISSUE TITLE
Add support for spatial data / NetTopologySuite to Oracle.EntityFrameworkCore

### ISSUE THREAD

**Issue by rtcpw** [oracle/dotnet-db-samples#327]
Hello. Could you please add support for [NetTopologySuite](https://learn.microsoft.com/en-us/ef/core/modeling/spatial) to `Oracle.EntityFrameworkCore`, so we can work with Oracle spatial types within Entity Framework Core?

Parts of this have been discussed in #89 and #190

**Comment by alexkeh** [comment]
Thanks for filing the feature request. We're going to evaluate which new features to implement in the coming year for EF Core once we release ODP.NET EF Core 8 support. 

If this feature (or any other feature request) is of interest, developers should give a thumbs up emoji to the feature request. The Oracle .NET team will take into account which features have the most community interest.

**Comment by Applesauce314** [comment]
I just upvoted this, but the NetTopologySuite documentation doesn't seem to mention anything about 3d solids which is the area I care about.
Unless I am wrong about this, could easily have missed something, then read my upvote as wanting support for spatial types, not specifically NetTopologySuite.

**Comment by Applesauce314** [comment]
followed up with https://github.com/NetTopologySuite/NetTopologySuite/discussions/730 and confirmed it does not handle 3d solids.
my use case is: given a set of 3d solid geometries, which geometry is a specific 3d point located in. if this feature can be done in a way that supports that, I'm interested, otherwise I'm not interested.

**Comment by alexkeh** [comment]
The [ODP.NET EFC NetTopologySuite package (preview)](https://www.nuget.org/packages/Oracle.EntityFrameworkCore.NetTopologySuite/10.23.26000-Preview.1) is now available. 

I am closing this feature request. If you encounter any bugs or issues with this new release, let us know by opening a new issue.

Here is the doc link to the [ODP.NET Spatial Data and NetTopologySuite](https://docs.oracle.com/en/database/oracle/oracle-database/26/odpnt/SpatialDataandNetTopologySuite.html) features.

**Comment by alexkeh** [comment]
If you encounter any bugs or need more features from the new Oracle.EntityFrameworkCore.NetTopologySuite assembly, create a new GitHub issue. Thanks!

**Comment by alexkeh** [comment]
@rtcpw Is the Oracle EF Core NTS assembly working for you? Any problems you encountered?

**Comment by rtcpw** [comment]
@alexkeh I have tested the NetTopologySuite for Oracle, and have encountered the following issue:

My table stores some polygons and multipolygons. Turns out, some of the shapes have invalid topologies due to incorrect hole specifications. The EF throws an exception when loading these shapes. I believe EF should load invalid topologies without throwing exceptions, because I can validate the topology myself through the `IsValid` geometry property.

**Comment by alexkeh** [comment]
@rtcpw Are you seeing this problem with the production version released today?

**Comment by rtcpw** [comment]
> Are you seeing this problem with the production version released today?

@alexkeh Yes, I am still seeing it even after updating to the latest production version. I have two invalid polygons in the table. One seems to be loaded without exceptions, and `IsValid` returns false, as expected and this is correct behavior. The other invalid polygon throws an exception during loading.

The exception details are:

```
ETYPE PolygonInterior inconsistent with expected POLYGON or POLYGON_EXTERIOR

NetTopologySuite.IO.Oracle

   at NetTopologySuite.IO.OracleGeometryReader.CreateMultiPolygon(GeometryFactory factory, Int32 dim, Int32 lrs, Double[] elemInfo, Int32 elemIndex, List`1 coords, Int32 numGeom)
   at NetTopologySuite.IO.OracleGeometryReader.Create(GeometryFactory factory, Int32 gType, SdoPoint point, Double[] elemInfo, Double[] ordinates)
   at NetTopologySuite.IO.OracleGeometryReader.Read(SdoGeometry geom)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.<PopulateIncludeCollection>g__ProcessCurrentElementRow|24_0[TIncludingEntity,TIncludedEntity](<>c__DisplayClass24_0`2& )
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.PopulateIncludeCollection[TIncludingEntity,TIncludedEntity](Int32 collectionId, QueryContext queryContext, DbDataReader dbDataReader, SingleQueryResultCoordinator resultCoordinator, Func`3 parentIdentifier, Func`3 outerIdentifier, Func`3 selfIdentifier, IReadOnlyList`1 parentIdentifierValueComparers, IReadOnlyList`1 outerIdentifierValueComparers, IReadOnlyList`1 selfIdentifierValueComparers, Func`5 innerShaper, INavigationBase inverseNavigation, Action`2 fixup, Boolean trackingQuery)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.<MoveNextAsync>d__20.MoveNext()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__67`1.MoveNext()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__67`1.MoveNext()
```

**Comment by alexkeh** [comment]
@rtcpw  Could you please share the schema and sample data for the spatial table? Based on the error, it appears that the `NetTopologySuite.IO.Oracle` library is unable to parse the polygon stored in the database.

We tested loading spatial data containing polygon and multipolygon geometries with incorrect hole specifications. In those cases, the data was loaded successfully using Oracle NTS EF Core, and `IsValid` returned false when validated on the EFC side. The behavior is consistent with Npgsql and SQL Server NTS EF providers as well.

I have attached the sample spatial data used for testing across Oracle, Npgsql, and SQL Server EF NTS providers.

[oracle.sql](https://github.com/user-attachments/files/26543829/oracle.sql)
[postgresql.sql](https://github.com/user-attachments/files/26543831/postgresql.sql)
[sqlserver.sql](https://github.com/user-attachments/files/26543830/sqlserver.sql)

**Comment by rtcpw** [comment]
@alexkeh I was able to get permission to share the following details. I have removed any extraneous columns and left only the relevant one.

The engine is `Oracle Standard Edition Two` running in AWS RDS.
19.0.0.0.ru-2026-01.spb-1.r3
`SPATIAL` option enabled via option group.

```sql
CREATE TABLE "MY_SHAPES"
(
	"SHAPE" "MDSYS"."SDO_GEOMETRY"
);
  
Insert into MY_SHAPES (SHAPE) values (MDSYS.SDO_GEOMETRY(2007, 8265, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 2003, 1, 27, 1003, 1, 94589, 2003, 1, 94599, 2003, 1, 94765, 2003, 1, 94813, 2003, 1, 94831, 2003, 1, 95145, 2003, 1, 95989, 2003, 1, 96161, 2003, 1, 96801, 2003, 1, 97961, 2003, 1, 97969, 2003, 1, 97977, 2003, 1, 97987, 2003, 1, 98023, 2003, 1, 98045, 2003, 1, 98075, 2003, 1, 98085, 2003, 1, 98151, 2003, 1, 98199, 2003, 1, 98209, 2003, 1, 98259, 2003, 1, 98281, 2003, 1, 98323, 2003, 1, 98375, 2003, 1, 98433, 2003, 1, 98479, 2003, 1, 98529, 2003, 1, 98575, 2003, 1, 98649, 2003, 1, 98665, 2003, 1, 98741, 2003, 1, 98783, 2003, 1, 98793, 2003, 1, 98843, 2003, 1, 98895, 2003, 1, 98945, 2003, 1, 98973, 2003, 1, 99037, 2003, 1, 99099, 2003, 1, 99167, 2003, 1, 99177, 2003, 1, 99273, 2003, 1, 99353, 2003, 1, 99397, 2003, 1, 99459, 2003, 1, 99499, 2003, 1, 99543, 2003, 1, 99587, 2003, 1, 99611, 2003, 1, 99669, 2003, 1, 99747, 2003, 1, 99789, 2003, 1, 99831, 2003, 1, 99859, 2003, 1, 99903, 2003, 1, 99913, 2003, 1, 100001, 2003, 1, 100047, 2003, 1, 100069, 2003, 1, 100131, 2003, 1, 100219, 2003, 1, 100243, 2003, 1, 100351, 2003, 1, 100405, 2003, 1, 100489, 2003, 1, 100563, 2003, 1, 100575, 2003, 1, 100623, 2003, 1, 100721, 2003, 1, 100763, 2003, 1, 100781, 2003, 1, 100791, 2003, 1, 100801, 2003, 1, 100847, 2003, 1, 100939, 2003, 1, 101001, 2003, 1, 101075, 2003, 1, 101135, 2003, 1, 101241, 2003, 1, 101359, 2003, 1, 101369, 2003, 1, 101429, 2003, 1, 101469, 2003, 1, 101555, 2003, 1, 101575, 2003, 1, 101621, 2003, 1, 101693, 2003, 1, 101799, 2003, 1, 101923, 2003, 1, 101977, 2003, 1, 102053, 2003, 1, 102137, 2003, 1, 102271, 2003, 1, 102351, 2003, 1, 102409, 2003, 1, 102473, 2003, 1, 102587, 2003, 1, 102665, 2003, 1, 102751, 2003, 1, 102813, 2003, 1, 102827, 2003, 1, 102915, 2003, 1, 103023, 2003, 1, 103039, 2003, 1, 103159, 2003, 1, 103245, 2003, 1, 103291, 2003, 1, 103357, 2003, 1, 103411, 2003, 1, 103553, 2003, 1, 103699, 2003, 1, 103761, 2003, 1, 103819, 2003, 1, 103935, 2003, 1, 104113, 2003, 1, 104149, 2003, 1, 104197, 2003, 1, 104211, 2003, 1, 104247, 2003, 1, 104333, 2003, 1, 104381, 2003, 1, 104489, 2003, 1, 104527, 2003, 1, 104595, 2003, 1, 104609, 2003, 1, 104639, 2003, 1, 104721, 2003, 1, 104855, 2003, 1, 104943, 2003, 1, 105031, 2003, 1, 105063, 2003, 1, 105169, 2003, 1, 105247, 2003, 1, 105335, 2003, 1, 105349, 2003, 1, 105471, 2003, 1, 105551, 2003, 1, 105641, 2003, 1, 105727, 2003, 1, 105827, 2003, 1, 105837, 2003, 1, 105881, 2003, 1, 105933, 2003, 1, 106031, 2003, 1, 106171, 2003, 1, 106215, 2003, 1, 106253, 2003, 1, 106275, 2003, 1, 106421, 2003, 1, 106513, 2003, 1, 106537, 2003, 1, 106643, 2003, 1, 106657, 2003, 1, 106739, 2003, 1, 106821, 2003, 1, 107027, 2003, 1, 107039, 2003, 1, 107227, 2003, 1, 107251, 2003, 1, 107341, 2003, 1, 107355, 2003, 1, 107373, 2003, 1, 107511, 2003, 1, 107561, 2003, 1, 107757, 2003, 1, 107949, 2003, 1, 108001, 2003, 1, 108097, 2003, 1, 108107, 2003, 1, 108263, 2003, 1, 108363, 2003, 1, 108517, 2003, 1, 108637, 2003, 1, 108671, 2003, 1, 108883, 2003, 1, 108993, 2003, 1, 109005, 2003, 1, 109163, 2003, 1, 109193, 2003, 1, 109571, 2003, 1, 109777, 2003, 1, 109795, 2003, 1, 109967, 2003, 1, 110015, 2003, 1, 110133, 2003, 1, 110291, 2003, 1, 110445, 2003, 1, 110543, 2003, 1, 110735, 2003, 1, 110875, 2003, 1, 111085, 2003, 1, 111227, 2003, 1, 111343, 2003, 1, 111793, 2003, 1, 112253, 2003, 1, 112393, 2003, 1, 112697, 2003, 1, 112915, 2003, 1, 112945, 2003, 1, 113025, 2003, 1, 113037, 2003, 1, 113383, 2003, 1, 113409, 2003, 1, 113693, 2003, 1, 114009, 2003, 1, 114049, 2003, 1, 114189, 2003, 1, 114297, 2003, 1, 114569, 2003, 1, 114607, 2003, 1, 115325, 2003, 1, 115599, 2003, 1, 115633, 2003, 1, 115983, 2003, 1, 116105, 2003, 1, 116259, 2003, 1, 116751, 2003, 1, 116857, 2003, 1, 116929, 2003, 1, 117207, 2003, 1, 117491, 2003, 1, 117599, 2003, 1, 117853, 2003, 1, 118203, 2003, 1, 118625, 2003, 1, 120553, 2003, 1, 120783, 2003, 1, 121045, 2003, 1, 121427, 2003, 1, 121899, 2003, 1, 122353, 2003, 1, 122803, 2003, 1, 123461, 1003, 1, 133161, 2003, 1, 133267, 1003, 1, 135489, 1003, 1, 138893, 1003, 1, 142837, 2003, 1, 142869, 2003, 1, 142939, 2003, 1, 143073, 2003, 1, 143203, 1003, 1, 144113, 1003, 1, 144939, 1003, 1, 145593, 1003, 1, 145647, 1003, 1, 146235, 2003, 1, 146297, 2003, 1, 146335, 1003, 1, 146943, 1003, 1, 147515, 1003, 1, 148215, 1003, 1, 148845, 1003, 1, 149157, 1003, 1, 149495, 1003, 1, 149975, 1003, 1, 150065, 1003, 1, 150249, 1003, 1, 150627, 1003, 1, 151099, 1003, 1, 151299, 2003, 1, 151387, 2003, 1, 151465, 1003, 1, 152215, 1003, 1, 152413, 1003, 1, 152599, 1003, 1, 152723, 1003, 1, 153039, 1003, 1, 153243, 1003, 1, 153389, 1003, 1, 153527, 1003, 1, 153631, 1003, 1, 153789, 1003, 1, 153941, 1003, 1, 154091, 2003, 1, 154311, 1003, 1, 154513, 1003, 1, 154629, 1003, 1, 154797, 1003, 1, 154939, 1003, 1, 155109, 1003, 1, 155247, 1003, 1, 155529, 1003, 1, 155653, 1003, 1, 155777, 1003, 1, 155879, 1003, 1, 156011, 1003, 1, 156089, 1003, 1, 156253, 1003, 1, 156387, 1003, 1, 156459, 1003, 1, 156543, 1003, 1, 156667, 1003, 1, 156773, 1003, 1, 156893, 1003, 1, 156981, 1003, 1, 157163, 1003, 1, 157353, 1003, 1, 157483, 1003, 1, 157567, 1003, 1, 157665, 1003, 1, 157835, 1003, 1, 157915, 1003, 1, 158049, 1003, 1, 158193, 1003, 1, 158347, 1003, 1, 158525, 1003, 1, 158603, 1003, 1, 158679, 1003, 1, 158751, 1003, 1, 158829, 1003, 1, 158977, 1003, 1, 159115, 1003, 1, 159225, 1003, 1, 159393, 1003, 1, 159471, 1003, 1, 159639, 1003, 1, 159785, 1003, 1, 159939, 1003, 1, 160005, 1003, 1, 160101, 1003, 1, 160121, 1003, 1, 160189, 1003, 1, 160245, 1003, 1, 160347, 1003, 1, 160417, 1003, 1, 160517, 1003, 1, 160631, 1003, 1, 160929, 1003, 1, 160993, 1003, 1, 161079, 1003, 1, 161147, 1003, 1, 161203, 1003, 1, 161325, 1003, 1, 161385, 1003, 1, 161443, 1003, 1, 161471, 1003, 1, 161535, 1003, 1, 161603, 1003, 1, 161713, 1003, 1, 161747, 1003, 1, 161907, 1003, 1, 161973, 1003, 1, 162065, 1003, 1, 162143, 1003, 1, 162207, 1003, 1, 162329, 1003, 1, 162463, 1003, 1, 162525, 1003, 1, 162597, 1003, 1, 162671, 1003, 1, 162711, 1003, 1, 162769, 1003, 1, 162797, 1003, 1, 162861, 1003, 1, 162923, 1003, 1, 162985, 1003, 1, 163007, 1003, 1, 163061, 1003, 1, 163149, 1003, 1, 163257, 1003, 1, 163305, 1003, 1, 163367, 1003, 1, 163419, 1003, 1, 163443, 1003, 1, 163507, 1003, 1, 163547, 1003, 1, 163597, 1003, 1, 163689, 1003, 1, 163757, 1003, 1, 163821, 1003, 1, 163879, 1003, 1, 163957, 1003, 1, 164009, 1003, 1, 164053, 1003, 1, 164077, 1003, 1, 164125, 1003, 1, 164179, 1003, 1, 164285, 1003, 1, 164351, 1003, 1, 164379, 1003, 1, 164393, 1003, 1, 164473, 1003, 1, 164561, 1003, 1, 164609, 1003, 1, 164665, 1003, 1, 164727, 1003, 1, 164825, 1003, 1, 164883, 1003, 1, 164943, 1003, 1, 164991, 1003, 1, 165011, 1003, 1, 165101, 1003, 1, 165143, 1003, 1, 165191, 1003, 1, 165217, 1003, 1, 165255, 1003, 1, 165341, 1003, 1, 165431, 1003, 1, 165565, 1003, 1, 165623, 1003, 1, 165763, 1003, 1, 165813, 1003, 1, 165891, 1003, 1, 165935, 1003, 1, 166025, 1003, 1, 166105, 1003, 1, 166153, 1003, 1, 166171, 1003, 1, 166209, 1003, 1, 166259, 1003, 1, 166317, 1003, 1, 166341, 1003, 1, 166387, 1003, 1, 166415, 1003, 1, 166441, 1003, 1, 166483, 1003, 1, 166513, 1003, 1, 166585, 1003, 1, 166623, 1003, 1, 166667, 1003, 1, 166693, 1003, 1, 166737, 1003, 1, 166759, 1003, 1, 166819, 1003, 1, 166871, 1003, 1, 166895, 1003, 1, 166939, 1003, 1, 167001, 1003, 1, 167045, 1003, 1, 167061, 1003, 1, 167097, 1003, 1, 167155, 1003, 1, 167179, 1003, 1, 167207, 1003, 1, 167231, 1003, 1, 167249, 1003, 1, 167267, 1003, 1, 167295, 1003, 1, 167325, 1003, 1, 167347, 1003, 1, 167383, 1003, 1, 167455, 1003, 1, 167513, 1003, 1, 167523, 1003, 1, 167561, 1003, 1, 167607, 1003, 1, 167661, 1003, 1, 167683, 1003, 1, 167695, 1003, 1, 167733, 1003, 1, 167779, 1003, 1, 167795, 1003, 1, 167819, 1003, 1, 167847, 1003, 1, 167887, 1003, 1, 167909, 1003, 1, 167935, 1003, 1, 167947, 1003, 1, 167963, 1003, 1, 168021, 1003, 1, 168033, 1003, 1, 168047, 1003, 1, 168103, 1003, 1, 168141, 1003, 1, 168165, 1003, 1, 168181, 1003, 1, 168199, 1003, 1, 168219, 1003, 1, 168265, 1003, 1, 168291, 1003, 1, 168311, 1003, 1, 168323, 1003, 1, 168345, 1003, 1, 168365, 1003, 1, 168375, 1003, 1, 168415, 1003, 1, 168453, 1003, 1, 168463, 1003, 1, 168515, 1003, 1, 168541, 1003, 1, 168559, 1003, 1, 168579, 1003, 1, 168589, 1003, 1, 168605, 1003, 1, 168627, 1003, 1, 168645, 1003, 1, 168663, 1003, 1, 168701, 1003, 1, 168731, 1003, 1, 168743, 1003, 1, 168761, 1003, 1, 168781, 1003, 1, 168793, 1003, 1, 168807, 1003, 1, 168825, 1003, 1, 168839, 1003, 1, 168875, 1003, 1, 168893, 1003, 1, 168907, 1003, 1, 168923, 1003, 1, 168935, 1003, 1, 168949, 1003, 1, 168959, 1003, 1, 168975, 1003, 1, 168991, 1003, 1, 169003, 1003, 1, 169015, 1003, 1, 169025, 1003, 1, 169039, 1003, 1, 169049, 1003, 1, 169059, 1003, 1, 169069, 1003, 1, 169083, 1003, 1, 169093, 1003, 1)));

CREATE INDEX "MY_SHAPES_SHAPE" ON "MY_SHAPES" ("SHAPE") INDEXTYPE IS "MDSYS"."SPATIAL_INDEX"  PARAMETERS (' SDO_INDX_DIMS=2 LAYER_GTYPE="COLLECTION"');
```

**Comment by alexkeh** [comment]
Thanks @rtcpw! We'll try it out.

**Comment by alexkeh** [comment]
@rtcpw 
The Oracle team replicated your issue using the provided data. Below is our analysis and recommended workaround.

### Error
The following exception is thrown by the `NetTopologySuite.IO.Oracle` library during geometry materialization:

```
System.ArgumentException: ELEM_INFO STARTING_OFFSET 1 inconsistent with ORDINATES length 0
at NetTopologySuite.IO.OracleGeometryReader.CreateMultiPolygon(...)
at NetTopologySuite.IO.OracleGeometryReader.Create(...)
at NetTopologySuite.IO.OracleGeometryReader.Read(SdoGeometry geom)
```
This is a valid and expected error given the data state in the spatial table (explained below).

Note: `NetTopologySuite.IO.Oracle` bridges the Oracle EF Core provider's conversion pipeline:
SDO_GEOMETRY → NTS geometry object → EF Core model column.

### Root Cause
From the data, a row has geometries defined with structural metadata (`SDO_ELEM_INFO_ARRAY`) but without coordinate data (`SDO_ORDINATE_ARRAY`).

Oracle Spatial does not strictly enforce the OGC Simple Features specification (https://www.ogc.org/standard/sfa/) at **insert time,** allowing such geometries to be stored.

However, NTS enforces this specification strictly at **construction time**. Since it defines geometries entirely in terms of coordinate sequences, a geometry without coordinates cannot be constructed. This is not a case of invalid geometry, but of non-constructible geometry.

This is distinct from topologically invalid geometries (e.g., incorrect holes, self-intersections), where both element info and coordinates are present. In those cases, NTS can still construct the geometry and it can be evaluated using `geometry.IsValid`. When coordinates are missing entirely, the failure occurs before validation — during object construction itself.

### Workaround
To avoid loading geometries that are missing ordinates or are otherwise invalid from the Oracle table, the following LINQ filter can be applied.

This ensures EF Core only materializes rows that will not cause a construction error:

`.Where(x => x.Shape.IsValid)`

The above LINQ translates to the following WHERE clause in SQL:

`WHERE SDO_GEOM.VALIDATE_GEOMETRY_WITH_CONTEXT(shape, 0.005) = 'TRUE'`
