### ISSUE TITLE
PublishTrimmed with Oracle.ManagedDataAccess.Core causes MSB6006 error

### ISSUE THREAD

**Issue by SIkebe** [oracle/dotnet-db-samples#52]
1. `dotnet new console`
1. `dotnet add package Oracle.ManagedDataAccess.Core --version 2.19.50`
1. `dotnet publish --runtime win-x64 /p:PublishTrimmed=true`

Error
```
dotnet publish --runtime win-x64 /p:PublishTrimmed=true
.NET Core 向け Microsoft (R) Build Engine バージョン 16.3.0+0f4c62fea
Copyright (C) Microsoft Corporation.All rights reserved.

  C:\work\Trimmed\Trimmed.csproj の復元が 20 ms で完了しました。
  Trimmed -> C:\work\Trimmed\bin\Debug\netcoreapp3.0\win-x64\Trimmed.dll
C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ILLink.targets(87,5): error MSB6006: "dotnet.exe" はコード -532462766 を伴って終了しました。 [C:\work\Trimmed\Trimmed.csproj]
```

**Comment by SIkebe** [comment]
with `/v:n`

```
Fatal error in IL Linker
         Unhandled exception. System.InvalidCastException: Unable to cast object of type 'System.Byte' to type 'System.String'.
            at Mono.Cecil.MetadataBuilder.GetConstantSignature(ElementType type, Object value)
            at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
            at Mono.Cecil.MetadataBuilder.AddField(FieldDefinition field)
            at Mono.Cecil.MetadataBuilder.AddFields(TypeDefinition type)
            at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
            at Mono.Cecil.MetadataBuilder.AddTypes()
            at Mono.Cecil.MetadataBuilder.BuildTypes()
            at Mono.Cecil.MetadataBuilder.BuildModule()
            at Mono.Cecil.MetadataBuilder.BuildMetadata()
            at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
            at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
            at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
            at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
            at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
            at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
            at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
            at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory)
            at Mono.Linker.Steps.OutputStep.OutputAssembly(AssemblyDefinition assembly)
            at Mono.Linker.Steps.OutputStep.ProcessAssembly(AssemblyDefinition assembly)
            at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
            at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
            at Mono.Linker.Pipeline.Process(LinkContext context)
            at Mono.Linker.Driver.Run(ILogger customLogger)
            at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
            at Mono.Linker.Driver.Main(String[] args)
```

**Comment by SIkebe** [comment]
FYI https://github.com/mono/linker/issues/729#issuecomment-531191484

**Comment by alexkeh** [comment]
The symptoms are the same as this issue: https://github.com/oracle/dotnet-db-samples/issues/42

It's the same error, package assembly, and stack.

That bug has been fixed already. If you have access to My Oracle Support, the patch can be requested as a one-off or you can wait until the next bundle patch is released.

The ODP.NET team hasn't decided when to release the next NuGet package. We just released 19.5. The fix should be in the next NuGet drop.

**Comment by SIkebe** [comment]
I tried 2.19.60 and confirmed that this issue fixed. Thank you @alexkeh !

**Comment by SIkebe** [comment]
2.19.60 compiled successfully but found another issue at runtime.
https://github.com/oracle/dotnet-db-samples/issues/54
