### ISSUE TITLE
Cannot publish trimmed single exe containing ODP Core

### ISSUE THREAD

**Issue by StephenDrewLDS** [oracle/dotnet-db-samples#86]
Hello,

I'm trying to publish a single trimmed netcoreapp3.1 exe containing Oracle.ManagedDataAccess,Core 2.19.80.

When I run it, it throws an error:

```
Exception has been thrown by the target of an invocation.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance[T]()
   at OracleInternal.ConnectionPool.PoolManager`3.CreateNewPR(Int32 reqCount, Boolean bForPoolPopulation, ConnectionString csWithDiffOrNewPwd, OracleConnection connRefForCriteria, String instanceName, List`1 switchFailedInstNames)
   at OracleInternal.ConnectionPool.PoolManager`3.Get(ConnectionString csWithDiffOrNewPwd, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)
   at OracleInternal.ConnectionPool.OraclePoolManager.Get(ConnectionString csWithNewPassword, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)
   at OracleInternal.ConnectionPool.OracleConnectionDispenser`3.Get(ConnectionString cs, PM conPM, ConnectionString pmCS, SecureString securedPassword, SecureString securedProxyPassword, OracleConnection connRefForCriteria)
   at Oracle.ManagedDataAccess.Client.OracleConnection.Open()
```

Any idea how I can resolve this?  It's a console tool and I'd really like to avoid shipping dozens of DLLs alongside it.

Thanks,
Steve

**Comment by sungam3r** [comment]
If your app uses reflection you can let the Tree Trimmer know by telling the project system about your Assembly, or even specific Types or Methods you don't want trimmed away. See docs https://docs.microsoft.com/en-us/dotnet/core/deploying/trim-self-contained#prevent-assemblies-from-being-trimmed

**Comment by alexkeh** [comment]
@StephenDrewLDS Does Microsoft provide guidance for ISVs to support trimming comprehensively? Or guidance when trimming Microsoft's own assemblies, such as ASP.NET Core, as a model ISVs can use? I haven't seen this guidance.

**Comment by alexkeh** [comment]
Closing the issue for now. 

The .NET Core doc notes indirect references, such as via reflection, must not be trimmed. The doc notes there are other scenarios in which trimming functionality will fail to detect references, but the only specific one listed is reflection. The doc also says,

"Trimming is an experimental feature in .NET Core 3.1 and is only available to applications that are published self-contained."
https://docs.microsoft.com/en-us/dotnet/core/deploying/trim-self-contained

When there's more comprehensive support and doc for trimming, I'll better be able to provide guidance on how ODP.NET Core can provide support.
