### ISSUE TITLE
System.TypeLoadException: Method 'Create' .net Core 3.1

### ISSUE THREAD

**Issue by deniscesar** [oracle/dotnet-db-samples#94]
I'm a beginner and I'm trying to run this example

https://github.com/oracle/dotnet-db-samples/blob/master/samples/dotnet-core/ef-core/autonomous-db/adb-odp-efcore.cs

My database already exists
But the following error is returning ... if you can help me

> Unhandled exception. System.TypeLoadException: Method Create in type Oracle.EntityFrameworkCore.Query.Internal.OracleQueryableMethodTranslatingExpressionVisitorFactory from assembly Oracle.EntityFrameworkCore, Version=3.1.19.0, Culture=neutral, PublicKeyToken=89b483f429c47342 does not have an implementation.
   at Microsoft.Extensions.DependencyInjection.OracleServiceCollectionExtensions.AddEntityFrameworkOracle(IServiceCollection serviceCollection)
   at Oracle.EntityFrameworkCore.Infrastructure.Internal.OracleOptionsExtension.ApplyServices(IServiceCollection services)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.ApplyServices(IDbContextOptions options, ServiceCollection services)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c__DisplayClass4_0.<GetOrAdd>g__BuildServiceProvider|3()
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c__DisplayClass4_0.<GetOrAdd>b__2(Int64 k)
   at System.Collections.Concurrent.ConcurrentDictionary2.GetOrAdd(TKey key, Func2 valueFactory)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options, Boolean providerRequired)
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet1.CheckState()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.Where[TSource](IQueryable1 source, Expression1 predicate)

Environment
.net core version 3.1.300
database first

Packages

>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.0-preview.8.20407.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="5.0.0-preview.8.20407.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.0-preview.8.20407.4">
    <PackageReference Include="Oracle.EntityFrameworkCore" Version="3.19.0-beta1" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="2.19.80" />

**Comment by alexkeh** [comment]
You're using EF Core 5 preview. Try downgrading to EF Core 3.1. Oracle EF Core does not yet support EF Core 5 yet.

We'll work on that support as soon as we wrap up the Oracle EF Core 3.1 driver, which should be very soon.

**Comment by deniscesar** [comment]
@alexkeh 
Thank you very much
Resolved!
