### ISSUE TITLE
Using ef core 3.1 mapping to a view fails

### ISSUE THREAD

**Issue by Martin-Andersen** [oracle/dotnet-db-samples#98]
I am using Oracle.EntityFrameworkCore 3.19.80

I am trying to map this view

 `create view CustomersWithPriContacts as
select c.ID       CustomerId,
       c.NAME     CustomerName,
       ctype.NAME CustomerType,
       ct.NAME    ContactName,
       ct.EMAIL   ContactEmail,
       ct.PHONE   ContactPhone
from CUSTOMER c
         left outer join CUSTOMER_TYPE ctype on c.CUSTOMER_TYPE_ID = ctype.ID
         left outer join CUSTOMER_CONTACT_MAP map on c.id = map.customer_id and map.CONTACT_TYPE_ID = 1
         left outer join CUSTOMER_CONTACT ct on ct.ID = map.CONTACT_ID
order by c.NAME;`

with this syntax

b.Entity<CustomersWithPrimaryContacts>().HasNoKey().ToView("CustomersWithPriContacts");

I am setting the schema first in the OnModelCreating
b.HasDefaultSchema("SAMSON");

getting the following error

`Oracle.ManagedDataAccess.Client.OracleException : ORA-00942: tabel eller view findes ikke
   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.VerifyExecution(OracleConnectionImpl connectionImpl, Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteReader(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl& rdrImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[] scnForExecution, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, Int64& internalInitialLOBFS, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Samson.Test.Integrations.FrontPageQuery.GetCustomersWithPrimaryContactsIfAny() in C:\Projects\samson\Samson\Samson.Test\Integrations\FrontPageQuery.cs:line 22
`

**Comment by alexkeh** [comment]
I believe ToView() is EF Core 2.x syntax, which is not supported in EF Core 3.1.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.relationalquerytypebuilderextensions.toview?view=efcore-2.2&viewFallbackFrom=efcore-3.1

**Comment by Martin-Andersen** [comment]
I am sorry, everything are working.
I was using a mapping convention builder for oracle and was calling it on each IEntityTypeConfiguration. What I wasn't aware off was the fact that it was applying it's convention for all models. shame on me.
So I am closing this "issue" and sending a thank you for the new ef core 3.1 provider
